Repository apache/incubator-devlake, pull requests merged in 2021-12, with the labels that each got.

#955 feat: collect all jira issue field in db
  plugins/jira/models/jira_issue.go
  plugins/jira/tasks/jira_issue_collector.go
Labels: feature

#956 feat: ae supports canceling
  plugins/ae/ae.go
  plugins/ae/tasks/ae_api_client.go
  plugins/ae/tasks/ae_commit_collector.go
  plugins/ae/tasks/ae_commit_converter.go
  plugins/ae/tasks/ae_project_collector.go
  plugins/core/apiclient.go
  plugins/core/errors.go
  utils/worker_scheduler.go
Labels: priority: medium

#975 `feat` #963 pipelines: create new pipeline
  config-ui/src/App.js
  config-ui/src/components/Sidebar/MenuConfiguration.jsx
  config-ui/src/components/menus/PipelinePresetsMenu.jsx
  config-ui/src/components/pipelines/ProviderSettings.jsx
  config-ui/src/components/widgets/PipelineIndicator.jsx
  config-ui/src/data/NullPipelineRun.js
  config-ui/src/hooks/usePipelineManager.jsx
  config-ui/src/hooks/usePipelineValidation.jsx
  config-ui/src/images/check-circle.svg
  config-ui/src/images/help.svg
  config-ui/src/images/help/github-help.png
  config-ui/src/images/help/gitlab-help.png
  config-ui/src/images/help/jira-help.png
  config-ui/src/images/layers.svg
  config-ui/src/images/no-synchronize.svg
  config-ui/src/images/refresh.svg
  config-ui/src/images/synchronize.svg
  config-ui/src/images/undo.svg
  config-ui/src/pages/configure/connections/AddConnection.jsx
  config-ui/src/pages/configure/connections/ConfigureConnection.jsx
  config-ui/src/pages/configure/integration/index.jsx
  config-ui/src/pages/configure/integration/manage.jsx
  config-ui/src/pages/configure/settings/jira.jsx
  config-ui/src/pages/pipelines/create.jsx
  config-ui/src/pages/triggers/index.jsx
  config-ui/src/styles/common.scss
  config-ui/src/styles/pipelines.scss
Labels: Frontend

#969 Go feishu
  .env.example
  config/config.go
  go.mod
  go.sum
  plugins/feishu/README-zh-CN.md
  plugins/feishu/README.md
  plugins/feishu/apimodels/meeting_top_user_item_result.go
  plugins/feishu/feishu.go
  plugins/feishu/init.go
  plugins/feishu/models/feishu_meeting_top_user_item.go
  plugins/jenkins/README.md
Labels: feature

#997 `feat` #965 pipelines: show pipeline activity & details
  config-ui/package-lock.json
  config-ui/package.json
  config-ui/src/App.js
  config-ui/src/components/pipelines/CodeInspector.jsx
  config-ui/src/components/pipelines/ProviderSettings.jsx
  config-ui/src/components/pipelines/StagePanel.jsx
  config-ui/src/components/pipelines/TaskActivity.jsx
  config-ui/src/data/NullPipelineTask.js
  config-ui/src/hooks/usePipelineManager.jsx
  config-ui/src/pages/pipelines/activity.jsx
  config-ui/src/pages/pipelines/create.jsx
  config-ui/src/pages/triggers/index.jsx
  config-ui/src/styles/pipelines.scss
  config-ui/src/utils/time.js
Labels: Frontend
