Repository apache/incubator-devlake, pull requests merged in 2021-08, with the labels that each got.

#130 feat: allow users to configure which branch to fetch for gitlab repos
  README.md
  src/plugins/gitlab-pond/src/collector/commits.js
  src/plugins/gitlab-pond/src/collector/index.js
  src/plugins/gitlab-pond/src/enricher/commits.js
  src/plugins/jira-pond/src/enricher/boards.js
Labels: enhancement

#132 Docker compose all services
  .gitignore
  CONTRIBUTING.md
  Dockerfile
  README.md
  concurrently.js
  config/docker.sample.js
  db/migrations/20210730102529-create-jira-board-issue.js
  db/mongo/connection.js
  db/postgresConnection.js
  docker-compose.prod.yml
  package.json
  src/collection/main.js
  src/enrichment/main.js
  src/plugins/index.js
  src/queue/consumer.js
Labels: enhancement

#146 feat: allow the migrations to be run while running the app in prod mode
  config/database.json
  package.json
Labels: enhancement

#186 chore: replace external resources with embedded assets
  docker-compose.yml
  grafana/dashboards/DeliveryCost.json
  grafana/dashboards/DeliveryEfficiency.json
  grafana/dashboards/DeliveryQuality.json
  grafana/dashboards/Homepage.json
  src/img/lake/1.png
  src/img/lake/2.png
  src/img/lake/3.png
  src/img/lake/4.png
  src/img/lake/5.png
  src/img/lake/delivery_capability.png
  src/img/lake/delivery_cost.png
  src/img/lake/delivery_efficiency.png
  src/img/lake/delivery_quality.png
  src/img/lake/delivery_value.png
  src/img/lake/logo.png
  src/img/lake/more.png
  src/img/lake/practice_cross_domain.png
  src/img/lake/practice_development.png
  src/img/lake/practice_operation.png
  src/img/lake/practice_requirement.png
  src/img/lake/practice_test.png
Labels: enhancement

#190 docs: add data source definition details to plugin references
  README.md
  docs/GRAFANA.md
  src/plugins/HOW-TO-ADD-METRICS.md
  src/plugins/README.md
Labels: docs

#195 docs: collaboration notes
  CONTRIBUTING.md
Labels: proposal

#182 feat: plugin configuration
  .gitignore
  config/constants.json
  config/docker.sample.js
  config/local.sample.js
  config/plugins.js
  config/plugins.sample.js
  db/mongo/connection.js
  simulate-new-setup.sh
  src/collection/worker.js
  src/dataCollectionLoop.js
  src/plugins/compound-figures/index.js
  src/plugins/gitlab-pond/README.md
  src/plugins/gitlab-pond/index.js
  src/plugins/gitlab-pond/src/collector/fetcher.js
  src/plugins/gitlab-pond/src/collector/index.js
  src/plugins/gitlab-pond/src/enricher/index.js
  src/plugins/index.js
  src/plugins/jira-pond/README.md
  src/plugins/jira-pond/index.js
  src/plugins/jira-pond/src/collector/fetcher.js
  src/plugins/jira-pond/src/collector/index.js
  src/plugins/jira-pond/src/enricher/index.js
  src/plugins/jira-pond/src/enricher/index.test.js
  src/plugins/jira-pond/src/enricher/issues.js
  src/queue/producer.js
  src/util/base.js
  src/util/jiraUser.js
  src/util/mapping.js
Labels: feature

#204 Sample config file doc updates
  config/docker.sample.js
  config/local.sample.js
  config/plugins.sample.js
Labels: docs

#209 docs: better docs, images and configuration
  src/plugins/gitlab-pond/README.md
Labels: docs

#203 docs: small formatting updates to plugin doc
  src/plugins/README.md
Labels: docs

#213 docs: general doc feedback from maxim v1
  README.md
  docs/DEVELOPER_SETUP.md
Labels: docs

#219 docs: add dashboard image to readme file
  README.md
Labels: docs

#208 docs: improves CONTRIBUTING.md
  CONTRIBUTING.md
  package-lock.json
Labels: docs

#211 docs: gitlab docs for config and summary
  src/plugins/gitlab-pond/README.md
Labels: docs

#214 docs: new and improved Jira pond readme
  src/plugins/jira-pond/README.md
Labels: docs

#179 docs: modify ts branch setup in readme
  .env.sample
  README.md
  devops/docker-compose.yml
Labels: docs

#217 feat: new command line interface for setting configs v0
  .gitignore
  NOTES.md
  README.md
  config/local.sample.js
  config/plugins.sample.js
  package-lock.json
  package.json
  scripts/command-line-config.js
  src/plugins/jira-pond/README.md
  src/plugins/jira-pond/src/collector/fetcher.js
Labels: feature

#227 docs: fix two small text updates in delivery efficiency dashboard
  grafana/dashboards/DeliveryEfficiency.json
Labels: docs

#234 fix: update local sample dev setup and adjust dev setup docs
  config/local.sample.js
  docs/DEVELOPER_SETUP.md
Labels: refactor

#222 chore(ci): update github actions
  .github/workflows/commit-msg.yml
  .github/workflows/coverage.yml
  .github/workflows/reviewdog.yml
  .github/workflows/test-e2e.yml
  .github/workflows/test.yml
Labels: enhancement

#223 feat: add typeorm module for rest api
  .env.sample
  apps/rest/src/app.module.ts
  apps/rest/src/models/base.ts
  apps/rest/src/models/index.spec.ts
  apps/rest/src/models/index.ts
  apps/rest/src/models/source.ts
  apps/rest/src/models/sourceTask.ts
  apps/rest/src/providers/typeorm.module.ts
  apps/rest/test/app.e2e-spec.ts
  package-lock.json
  package.json
Labels: feature

#181 docs: adding issue templates and pull request templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/proposal.md
  .github/ISSUE_TEMPLATE/question.md
  .github/pull_request_template.md
Labels: docs

#185 docs: minor fixes to readme to help developers set up
  .env.sample
  README.md
  devops/docker-compose.yml
  grafana/grafana.config
  grafana/img/grafana_icon.svg
  package-lock.json
  package.json
Labels: docs

#238 fix: remove some gitub config on the main branch
  .github/codecov.yml
  .github/workflows/commit-msg.yml
  .github/workflows/coverage.yml
  .github/workflows/main.yml
  .github/workflows/reviewdog.yml
  .github/workflows/test-e2e.yml
  .github/workflows/test.yml
Labels: bug

#236 docs: added type mapping and jira status mapping to docs
  README.md
  docs/DEVELOPER_SETUP.md
Labels: docs

#240 fix: remove duplicate issue template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: docs

#172 feat: add events service to make event broadcast between app instances
  .github/workflows/coverage.yml
  .github/workflows/test-e2e.yml
  .github/workflows/test.yml
  apps/core/events/events.module.spec.ts
  apps/core/events/events.module.ts
  apps/core/events/events.service.ts
  apps/core/events/index.ts
  apps/core/test/events.e2e-spec.ts
  apps/queue/test/app.e2e-spec.ts
  apps/rest/test/jest-e2e.json
  jest-e2e.json
  package-lock.json
  package.json
Labels: proposal

#244 feat(Ts): plugin templates
  apps/queue/src/consumer/index.ts
  apps/queue/src/consumer/plugins.ts
  apps/queue/src/consumer/service.ts
  package.json
  plugins/README.md
  plugins/core/src/base.entity.ts
  plugins/core/src/collector.ts
  plugins/core/src/dependency.resolver.ts
  plugins/core/src/enricher.ts
  plugins/core/src/executable.interface.ts
  plugins/core/src/exports.decorator.ts
  plugins/core/src/imports.decorator.ts
  plugins/core/src/plugin.interface.ts
  plugins/core/src/plugin.ts
  plugins/core/src/plugins.module.ts
  plugins/core/src/task.interface.ts
  plugins/core/test/plugin.spec.ts
  plugins/jira/src/index.ts
  plugins/jira/src/migrates/1629304465163-initialize.ts
  plugins/jira/src/tasks/issue/issue.collector.ts
  plugins/jira/src/tasks/issue/issue.entity.ts
  plugins/jira/src/tasks/issue/issue.spec.ts
  plugins/jira/src/tasks/leadtime/leadtime.enricher.ts
  plugins/jira/src/tasks/leadtime/leadtime.entity.ts
  plugins/jira/src/tasks/leadtime/leadtime.spec.ts
  plugins/jira/test/index.spec.ts
Labels: feature

#242 feat: source api implement
  apps/rest/README.md
  apps/rest/src/app.module.ts
  apps/rest/src/controllers/source.spec.ts
  apps/rest/src/controllers/source.ts
  apps/rest/src/controllers/sourceTask.ts
  apps/rest/src/models/source.ts
  apps/rest/src/services/source.spec.ts
  apps/rest/src/services/source.ts
  apps/rest/src/services/sourceTask.ts
  apps/rest/src/types/pagination.ts
  apps/rest/src/types/source.ts
  apps/rest/src/types/sourceTask.ts
  apps/rest/test/__snapshots__/source.e2e-spec.ts.snap
  apps/rest/test/source.e2e-spec.ts
  apps/rest/test/utils.ts
  package-lock.json
  package.json
Labels: feature

#262 Feat/source api
  .env.sample
  .gitignore
  README.md
  apps/rest/src/app.module.ts
  apps/rest/src/controllers/source.spec.ts
  apps/rest/src/controllers/sourceTask.spec.ts
  apps/rest/src/controllers/sourceTask.ts
  apps/rest/src/models/source.ts
  apps/rest/src/services/source.ts
  apps/rest/src/services/sourceTask.spec.ts
  apps/rest/src/services/sourceTask.ts
  apps/rest/src/types/pagination.ts
  apps/rest/src/types/sourceTask.ts
  apps/rest/test/__snapshots__/source.e2e-spec.ts.snap
  devops/docker-compose.yml
  grafana/provisioning/datasources/datasource.yml
  package.json
  plugins/core/src/dependency.resolver.ts
  plugins/jira/src/index.ts
  plugins/jira/src/migrates/1629304465163-initialize.ts
  plugins/jira/src/tasks/issue/issue.collector.ts
  plugins/jira/src/tasks/leadtime/leadtime.enricher.ts
  plugins/jira/src/tasks/leadtime/leadtime.spec.ts
Labels: feature

#255 feat: task service with plugin execution
  apps/core/events/events.module.spec.ts
  apps/core/events/events.module.ts
  apps/core/events/events.service.ts
  apps/core/tasks/index.ts
  apps/core/tasks/task.model.ts
  apps/core/tasks/tasks.module.ts
  apps/core/tasks/tasks.services.ts
  apps/core/tasks/tasks.spec.ts
  apps/core/test/events.e2e-spec.ts
  apps/core/test/tasks.e2e-spec.ts
  apps/queue/src/consumer/index.ts
  apps/queue/src/consumer/service.ts
  apps/queue/src/producer/index.ts
  apps/queue/src/producer/service.ts
  apps/queue/src/queue.module.ts
  apps/queue/test/app.e2e-spec.ts
  apps/queue/tsconfig.app.json
  devops/docker-compose.yml
  jest-e2e.json
  nest-cli.json
  package.json
  plugins/core/src/dependency.resolver.ts
  plugins/core/src/exports.decorator.ts
  plugins/core/src/plugin.interface.ts
  plugins/core/src/plugins.module.ts
  plugins/core/test/plugin.spec.ts
  plugins/jira/src/index.ts
  plugins/jira/src/tasks/changelog/changelog.collector.ts
  plugins/jira/src/tasks/changelog/changelog.entity.ts
  plugins/jira/src/tasks/changelog/changelog.spec.ts
  plugins/jira/src/tasks/index.ts
  plugins/jira/src/tasks/issue/issue.collector.ts
  plugins/jira/src/tasks/leadtime/leadtime.enricher.ts
  scripts/producer.ts
  scripts/tsconfig.script.json
Labels: feature

#270 feat: Adding make, grafana and docker to our project
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/proposal.md
  .github/ISSUE_TEMPLATE/question.md
  .github/pull_request_template.md
  .github/workflows/commit-msg.yml
  .gitignore
  Makefile
  README.md
  devops/docker-compose.yml
  grafana/dashboards/CompoundFigures.json
  grafana/dashboards/Home.json
  grafana/grafana.config
  grafana/img/grafana_icon.svg
  grafana/provisioning/dashboards/dashboard.yml
  grafana/provisioning/datasources/datasource.yml
Labels: enhancement

#273 First go test
  .github/workflows/commit-msg.yml
  .github/workflows/test.yml
  Makefile
  go.mod
  test/example/greetings.go
  test/example/greetings_test.go
Labels: enhancement
