Repository apache/incubator-devlake, pull requests merged in 2021-09, with the labels that each got.

#320 Gitlab collection - Merge Requests, Reviewers and Notes
  models/base.go
  plugins/gitlab/gitlab.go
  plugins/gitlab/init.go
  plugins/gitlab/models/gitlabMergeRequest.go
  plugins/gitlab/models/gitlabMergeRequestNote.go
  plugins/gitlab/models/gitlabReviewers.go
  plugins/gitlab/models/gitlabcommit.go
  plugins/gitlab/models/gitlabproject.go
  plugins/gitlab/tasks/gitlabMergeRequestCollector.go
  plugins/gitlab/tasks/gitlabMergeRequestNote.go
  plugins/gitlab/tasks/gitlabMergeRequestReviewer.go
Labels: enhancement

#319 feat: add worker_scheduler for parallelization
  config/config.go
  go.mod
  go.sum
  plugins/jira/tasks/jiraapiclient.go
  plugins/jira/tasks/jirachangelogcollector.go
  plugins/jira/tasks/jiraissuecollector.go
  plugins/plugins.go
  utils/worker_scheduler.go
  utils/worker_scheduler_test.go
Labels: feature

#334 docs: add user setup in readme
  Dockerfile
  README.md
  devops/docker-compose.yml
Labels: docs

#336 Gitlab pagination continued
  devops/docker-compose.yml
  logger/log.go
  plugins/gitlab/gitlab.go
  plugins/gitlab/models/gitlab_commit.go
  plugins/gitlab/models/gitlab_merge_request.go
  plugins/gitlab/models/gitlab_merge_request_note.go
  plugins/gitlab/models/gitlab_project.go
  plugins/gitlab/models/gitlab_reviewer.go
  plugins/gitlab/tasks/common.go
  plugins/gitlab/tasks/gitlabMergeRequestCollector.go
  plugins/gitlab/tasks/gitlabMergeRequestNote.go
  plugins/gitlab/tasks/gitlab_api_client.go
  plugins/gitlab/tasks/gitlab_commit_collector.go
  plugins/gitlab/tasks/gitlab_merge_request_collector.go
  plugins/gitlab/tasks/gitlab_merge_request_note.go
  plugins/gitlab/tasks/gitlab_merge_request_reviewer.go
  plugins/gitlab/tasks/gitlab_project_collector.go
  plugins/gitlab/tasks/gitlabcommitcollector.go
  plugins/jira/tasks/jiraapiclient.go
Labels: enhancement

#339 feat: adds FirstCommentTime to GL MRs
  plugins/gitlab/README.md
  plugins/gitlab/models/gitlab_merge_request.go
  plugins/gitlab/models/gitlab_merge_request_note.go
  plugins/gitlab/tasks/gitlab_merge_request_collector.go
  plugins/gitlab/tasks/gitlab_merge_request_note.go
Labels: enhancement

#314 using json tag and gorm tag to simply convert results
  plugins/jira/models/jiraissue.go
  plugins/jira/tasks/jiraapiclient.go
  plugins/jira/tasks/jirachangelogcollector.go
  plugins/jira/tasks/jiraissuecollector.go
  plugins/jira/tasks/jiraissueenricher.go
Labels: proposal

#376 Style config UI
  Makefile
  config-ui/.dockerignore
  config-ui/components/Content.js
  config-ui/components/Nav.js
  config-ui/components/Sidebar.js
  config-ui/package.json
  config-ui/pages/_app.js
  config-ui/pages/index.js
  config-ui/styles/Content.module.css
  config-ui/styles/Home.module.css
  config-ui/styles/Nav.module.css
  config-ui/styles/Sidebar.module.css
  config-ui/styles/globals.css
  config-ui/ui.Dockerfile
  config-ui/utils/envValue.js
  docker-compose.yml
Labels: enhancement

#410 feat: replace native alert with in browser dialog
  config-ui/components/SaveAlert.jsx
  config-ui/pages/index.jsx
  config-ui/pages/plugins/gitlab.jsx
  config-ui/pages/plugins/jenkins.jsx
  config-ui/pages/plugins/jira.jsx
Labels: enhancement

#411 fix: new form placeholders and add extra jira field
  config-ui/pages/plugins/gitlab.jsx
  config-ui/pages/plugins/jenkins.jsx
  config-ui/pages/plugins/jira.jsx
Labels: enhancement

#412 feat: add new required forms setup and help icons
  config-ui/pages/index.jsx
  config-ui/pages/plugins/gitlab.jsx
  config-ui/pages/plugins/jenkins.jsx
  config-ui/pages/plugins/jira.jsx
  config-ui/styles/Home.module.css
  config-ui/styles/libraries/blueprint.css
Labels: enhancement

#434 feat: domain layer plugin
  plugins/domainlayer/README.md
  plugins/domainlayer/domainlayer.go
  plugins/domainlayer/models/base/base.go
  plugins/domainlayer/models/code/commit.go
  plugins/domainlayer/models/code/note.go
  plugins/domainlayer/models/code/pr.go
  plugins/domainlayer/models/code/repo.go
  plugins/domainlayer/models/devops/pipeline.go
  plugins/domainlayer/models/ticket/board.go
  plugins/domainlayer/models/ticket/issue.go
Labels: iter1

#439 feat: set OriginKey as primary to support indate
  plugins/domainlayer/models/base/base.go
Labels: proposal

#441 fix: badge error in README.md
  .gitignore
  README.md
Labels: docs

#446 feat: add type and status mappings to jira plugin
  config-ui/next.config.js
  config-ui/pages/plugins/gitlab/index.jsx
  config-ui/pages/plugins/jenkins/index.jsx
  config-ui/pages/plugins/jira.jsx
  config-ui/pages/plugins/jira/ClearButton.jsx
  config-ui/pages/plugins/jira/MappingTag.jsx
  config-ui/pages/plugins/jira/MappingTagStatus.jsx
  config-ui/pages/plugins/jira/index.jsx
  config-ui/pages/triggers/index.jsx
  config-ui/styles/Home.module.css
  config-ui/styles/libraries/blueprint.css
  config-ui/utils/findStrBetween.js
  config-ui/utils/readAndSet.jsx
Labels: feature
