Repository apache/incubator-devlake, pull requests merged in 2022-11, with the labels that each got.

#3626 refactor: update integration context initial props
  config-ui/src/store/integrations-context.jsx
Labels: pr-type/refactor, component/config-ui

#3666 fix: add optional chain check for null entity name
  config-ui/src/models/GithubProject.js
  config-ui/src/models/JenkinsJob.js
Labels: pr-type/bug-fix, component/config-ui

#3738 feat: add a 'Bugs to be Triaged' panel
  grafana/dashboards/WeeklyBugRetro.json
Labels: pr-type/feature-development

#3743 feat: add proxy api for github
  plugins/github/api/proxy.go
  plugins/github/impl/impl.go
Labels: pr-type/feature-development

#3764 Issues/3234 add parallelLabels for blueprint/pipeline
  api/blueprints/blueprints.go
  api/pipelines/pipelines.go
  config-ui/src/hooks/usePipelineManager.jsx
  config-ui/src/pages/blueprints/blueprint-detail.jsx
  config-ui/src/pages/blueprints/create-blueprint.jsx
  models/blueprint.go
  models/migrationscripts/20221115_add_labels.go
  models/migrationscripts/register.go
  models/pipeline.go
  plugins/helper/api_async_client.go
  plugins/helper/worker_scheduler.go
  plugins/helper/worker_scheduler_test.go
  services/blueprint.go
  services/blueprint_helper.go
  services/pipeline.go
  services/pipeline_helper.go
  services/pipeline_runner.go
  utils/slice.go
  utils/slice_test.go
Labels: pr-type/feature-development
