Repository apache/incubator-devlake, pull requests merged in 2022-02, with the labels that each got.

#1178 Update README
  README.md
Labels: component/docs

#1177 `feat`: setup multi-selectors for jira issue types w/ api proxy | `1064`
  config-ui/src/components/ClearButton.jsx
  config-ui/src/hooks/useJIRA.jsx
  config-ui/src/pages/configure/mock-data/jira/fields.js
  config-ui/src/pages/configure/mock-data/jira/issueTypes.js
  config-ui/src/pages/configure/settings/jira.jsx
  config-ui/src/styles/libraries/blueprint.scss
Labels: type/feature-development

#1203 feat: create pipeline - advanced pipeline mode | `1127`
  config-ui/package-lock.json
  config-ui/package.json
  config-ui/src/components/menus/PipelinePresetsMenu.jsx
  config-ui/src/components/widgets/PipelineIndicator.jsx
  config-ui/src/data/pipeline-config-samples/default.js
  config-ui/src/data/pipeline-config-samples/gitextractor.js
  config-ui/src/data/pipeline-config-samples/github.js
  config-ui/src/data/pipeline-config-samples/gitlab.js
  config-ui/src/data/pipeline-config-samples/jenkins.js
  config-ui/src/data/pipeline-config-samples/jira.js
  config-ui/src/data/pipeline-config-samples/refdiff.js
  config-ui/src/hooks/usePipelineManager.jsx
  config-ui/src/hooks/usePipelineValidation.jsx
  config-ui/src/pages/pipelines/activity.jsx
  config-ui/src/pages/pipelines/create.jsx
  config-ui/src/pages/pipelines/index.jsx
  config-ui/src/styles/common.scss
  config-ui/src/styles/pipelines.scss
Labels: type/feature-development, component/config-ui

#1236 fix gitextractor arguments validation
  plugins/gitextractor/gitextractor.go
  plugins/gitextractor/main.go
Labels: type/bug-fix

#1260 fix: gitlab provider - disable project id mappings field
  config-ui/src/pages/configure/connections/ConfigureConnection.jsx
  config-ui/src/pages/configure/settings/gitlab.jsx
  plugins/gitlab/README.md
Labels: type/bug-fix, component/config-ui

#1267 feat: collect gitlab tags
  plugins/gitlab/gitlab.go
  plugins/gitlab/models/gitlab_tag.go
  plugins/gitlab/tasks/gitlab_tag_collector.go
Labels: type/feature-request, project/ee

#1268 `fix`: create pipeline : optimize advanced menu accessibility
  config-ui/src/components/menus/PipelineConfigsMenu.jsx
  config-ui/src/components/menus/PipelinePresetsMenu.jsx
  config-ui/src/pages/pipelines/create.jsx
Labels: type/bug-fix, component/config-ui
