Repository apache/incubator-devlake, pull requests merged in 2022-09, with the labels that each got.

#2859 feat: setup database migration alert dialog on ui
  config-ui/src/App.js
  config-ui/src/components/MigrationAlertDialog.jsx
  config-ui/src/components/Toast.jsx
  config-ui/src/components/loaders/ContentLoader.jsx
  config-ui/src/config/migration.js
  config-ui/src/hooks/useDatabaseMigrations.jsx
  config-ui/src/pages/blueprints/create-blueprint.jsx
  config-ui/src/utils/request.js
Labels: pr-type/feature-development, component/config-ui

#2903 fix: add missing jenkins proxy field on save
  config-ui/src/hooks/useConnectionManager.jsx
Labels: pr-type/bug-fix, component/config-ui

#2980 fix: fix bug on update time
  config-ui/src/components/pipelines/StageTaskName.jsx
Labels: pr-type/bug-fix

#2993 feat: change duration from text to float8
  plugins/gitlab/models/job.go
  plugins/gitlab/models/migrationscripts/20220906_fix_duration_to_float8.go
  plugins/gitlab/models/migrationscripts/register.go
Labels: pr-type/bug-fix

#3052 feat: finish pipeline and issue webhook
  plugins/gitlab/tasks/pipeline_project_convertor.go
  plugins/webhook/api/cicd_pipeline.go
  plugins/webhook/api/cicd_pipeline_test.go
  plugins/webhook/api/issue.go
  plugins/webhook/impl/impl.go
Labels: pr-type/feature-development

#2995 feat(config-ui): added prettier to help format code
  config-ui/.eslintrc
  config-ui/.prettierignore
  config-ui/.prettierrc.js
  config-ui/package-lock.json
  config-ui/package.json
Labels: component/config-ui

#3139 Issues/3023 add hook-URL in connections API
  plugins/webhook/api/connection.go
Labels: pr-type/bug-fix

#3017 feat(config-ui): added a data integration webhook
  config-ui/package-lock.json
  config-ui/package.json
  config-ui/src/.babelrc
  config-ui/src/App.js
  config-ui/src/components/Sidebar/MenuConfiguration.jsx
  config-ui/src/hooks/useWebhookManager.jsx
  config-ui/src/images/icons/copy.svg
  config-ui/src/images/icons/delete.svg
  config-ui/src/images/icons/setting-con.svg
  config-ui/src/images/icons/vector.svg
  config-ui/src/images/integrations/webhook.svg
  config-ui/src/pages/configure/integration/index.jsx
  config-ui/src/pages/connections/webhook/add-modal.jsx
  config-ui/src/pages/connections/webhook/delete-modal.jsx
  config-ui/src/pages/connections/webhook/index.jsx
  config-ui/src/pages/connections/webhook/styled.js
  config-ui/src/pages/connections/webhook/view-or-edit-modal.jsx
Labels: pr-type/refactor, pr-type/feature-development, component/config-ui

#3157 refactor: webpack & eslint - disable autofix on startup compile
  config-ui/webpack.config.js
Labels: pr-type/refactor, component/config-ui

#3110 fix: config-ui - database migration handler update
  config-ui/src/hooks/useDatabaseMigrations.jsx
Labels: pr-type/bug-fix, component/config-ui

#3246 fix: github transformation - add dora label to github incident group
  config-ui/src/pages/configure/settings/github.jsx
  config-ui/src/pages/configure/settings/jira.jsx
Labels: pr-type/bug-fix, component/config-ui

#3258 fix 2 bug in jira blueprint
  config-ui/src/hooks/useDataScopesManager.jsx
  config-ui/src/hooks/useJIRA.jsx
  config-ui/src/pages/configure/settings/jira.jsx
  plugins/jira/e2e/issue_test.go
  plugins/jira/e2e/snapshot_tables/_tool_jira_issues.csv
  plugins/jira/e2e/snapshot_tables/issues.csv
  plugins/jira/tasks/issue_extractor.go
Labels: pr-type/bug-fix

#3260 fix: fix migration dialog only appear after refresh
  config-ui/src/App.js
  config-ui/src/config/migration.js
  config-ui/src/hooks/useDatabaseMigrations.jsx
  config-ui/src/utils/request.js
Labels: type/bug

#3265 fix: duration only cal how long beganAt to now when status is running or created
  config-ui/src/pages/blueprints/blueprint-detail.jsx
Labels: pr-type/bug-fix

#3267 fix: tell error correctly when duplicate name
  config-ui/src/hooks/useConnectionManager.jsx
Labels: pr-type/bug-fix

#3275 fix: add array checks to all chosen tags for jira boards
  config-ui/src/components/blueprints/BoardsSelector.jsx
  config-ui/src/hooks/useJIRA.jsx
  config-ui/src/pages/blueprints/blueprint-detail.jsx
  config-ui/src/pages/configure/settings/jira.jsx
Labels: pr-type/bug-fix, component/config-ui

#3291 fix: change some wording
  config-ui/src/pages/connections/incoming-webhook/add-modal.jsx
  config-ui/src/pages/connections/incoming-webhook/view-or-edit-modal.jsx
Labels: pr-type/bug-fix
