Repository apache/incubator-devlake, pull requests merged in 2022-04, with the labels that each got.

#1436 `fix` `v0.9.2` config ui - update menu labels and titles for pipelines
  config-ui/src/components/Sidebar/MenuConfiguration.jsx
  config-ui/src/pages/pipelines/create.jsx
  config-ui/src/pages/pipelines/index.jsx
Labels: component/config-ui

#1444 `fix` `v0.9.2` data integrations - configure connection form ux updates
  config-ui/src/components/validation/InputValidationError.jsx
  config-ui/src/data/Providers.js
  config-ui/src/pages/configure/connections/ConfigureConnection.jsx
  config-ui/src/pages/configure/connections/ConnectionForm.jsx
  config-ui/src/styles/integration.scss
Labels: enhancement, component/config-ui

#1390 `fix`: config-ui : error handling updates for network requests
  config-ui/cypress/fixtures/jira-sources.json
  config-ui/cypress/fixtures/new-gitextractor-pipeline-tasks.json
  config-ui/cypress/fixtures/new-gitextractor-pipeline.json
  config-ui/cypress/fixtures/new-github-pipeline-tasks.json
  config-ui/cypress/fixtures/new-github-pipeline.json
  config-ui/cypress/fixtures/new-gitlab-pipeline-tasks.json
  config-ui/cypress/fixtures/new-gitlab-pipeline.json
  config-ui/cypress/fixtures/new-jenkins-pipeline-tasks.json
  config-ui/cypress/fixtures/new-jenkins-pipeline.json
  config-ui/cypress/fixtures/new-jira-connection.json
  config-ui/cypress/fixtures/new-jira-pipeline-tasks.json
  config-ui/cypress/fixtures/new-jira-pipeline.json
  config-ui/cypress/fixtures/new-refdiff-pipeline-tasks.json
  config-ui/cypress/fixtures/new-refdiff-pipeline.json
  config-ui/cypress/fixtures/pipeline-activity.json
  config-ui/cypress/fixtures/pipeline-tasks.json
  config-ui/cypress/fixtures/pipelines.json
  config-ui/cypress/integration/0-api/api.spec.js
  config-ui/cypress/integration/2-data-integrations/providers.spec.js
  config-ui/cypress/integration/3-pipelines/create-new.spec.js
  config-ui/cypress/integration/3-pipelines/manage.spec.js
  config-ui/src/hooks/useConnectionManager.jsx
  config-ui/src/hooks/useJIRA.jsx
  config-ui/src/hooks/usePipelineManager.jsx
  config-ui/src/pages/configure/connections/AddConnection.jsx
  config-ui/src/pages/configure/connections/ConnectionForm.jsx
  config-ui/src/pages/configure/integration/manage.jsx
  config-ui/src/pages/configure/settings/jira.jsx
  config-ui/src/pages/pipelines/index.jsx
  config-ui/src/styles/integration.scss
  config-ui/src/utils/request.js
Labels: type/bug-fix, component/config-ui

#1522 refactor: rename some fields
  models/domainlayer/code/pull_request.go
  models/domainlayer/code/refs_commits_diff.go
  models/domainlayer/crossdomain/refs_issues_diff.go
  models/domainlayer/ticket/issue.go
  models/migrationscripts/archived/issue.go
  models/migrationscripts/archived/pull_request.go
  models/migrationscripts/archived/ref.go
  plugins/github/tasks/issue_converter.go
  plugins/jira/tasks/issue_converter.go
  plugins/refdiff/tasks/refs_commits_diffs_calculator.go
Labels: type/refactor

#1553 fix: passing an incorrect parameter value
  plugins/jira/tasks/apiv2models/issue.go
Labels: type/bug-fix

#1541 fix(framework): return the result of retry instead of assign it to err
  e2e/gitlab_merge_request_commits_merge_requests_test.go
  e2e/gitlab_merge_request_commits_test.go
  e2e/gitlab_mrs_test.go
  plugins/gitlab/tasks/gitlab_shared.go
  plugins/gitlab/tasks/merge_request_comment_converter.go
  plugins/gitlab/tasks/merge_request_commits_converter.go
  plugins/helper/api_async_client.go
Labels: type/bug-fix

#1577 Fix gitlab mr converter
  plugins/gitlab/models/gitlab_merge_request.go
  plugins/gitlab/models/gitlab_user.go
  plugins/gitlab/models/migrationscripts/archived/merge_request.go
  plugins/gitlab/tasks/merge_request_converter.go
  plugins/gitlab/tasks/merge_request_extractor.go
Labels: type/bug-fix

#1578 Fix domain pull request
  models/domainlayer/code/pull_request.go
  models/domainlayer/crossdomain/pull_request_issue.go
  models/migrationscripts/archived/pull_request.go
  plugins/github/models/github_pull_request_issue.go
  plugins/github/models/migrationscripts/archived/pull_request.go
  plugins/github/models/migrationscripts/archived/pull_request_issue.go
  plugins/github/tasks/pull_request_converter.go
  plugins/github/tasks/pull_request_issue_enricher.go
  plugins/github/tasks/pull_request_issues_convertor.go
  plugins/gitlab/models/gitlab_user.go
  plugins/gitlab/tasks/merge_request_converter.go
Labels: type/bug-fix

#1472 `feat` config-ui : implement pipeline blueprints
  config-ui/package-lock.json
  config-ui/package.json
  config-ui/src/App.js
  config-ui/src/components/Sidebar/MenuConfiguration.jsx
  config-ui/src/components/blueprints/AddBlueprintDialog.jsx
  config-ui/src/components/blueprints/BlueprintsGrid.jsx
  config-ui/src/components/blueprints/DeletePopover.jsx
  config-ui/src/components/blueprints/PipelineTasks.jsx
  config-ui/src/components/loaders/ContentLoader.jsx
  config-ui/src/data/NullBlueprint.js
  config-ui/src/hooks/useBlueprintManager.jsx
  config-ui/src/hooks/useBlueprintValidation.jsx
  config-ui/src/hooks/usePipelineManager.jsx
  config-ui/src/hooks/usePipelineValidation.jsx
  config-ui/src/images/blueprints.png
  config-ui/src/images/calendar-3.png
  config-ui/src/images/calendar-4.png
  config-ui/src/pages/blueprints/index.jsx
  config-ui/src/pages/pipelines/create.jsx
  config-ui/src/pages/pipelines/index.jsx
  config-ui/src/styles/integration.scss
  config-ui/src/utils/request.js
Labels: enhancement, type/feature-development, component/config-ui

#1588 `fix` config-ui: qa testing fixes release v0.10.0
  config-ui/src/components/blueprints/AddBlueprintDialog.jsx
  config-ui/src/images/cron-help.png
  config-ui/src/pages/blueprints/index.jsx
  config-ui/src/pages/configure/integration/manage.jsx
  config-ui/src/pages/pipelines/create.jsx
Labels: enhancement, type/bug-fix

#1597 chore(refdiff): modify docs and .env
  .env.example
  plugins/refdiff/README-zh-CN.md
  plugins/refdiff/README.md
Labels: type/bug-fix

#1593 Support k8s deployment
  .env.example
  .github/workflows/build.yml
  config-ui/nginx.conf
  config-ui/nginx.sh
  docker-compose-temporal.yml
  docker-compose.yml
Labels: type/feature-development

#1617 fix: #1585
  plugins/refdiff/tasks/refs_commits_diffs_calculator.go
  plugins/refdiff/tasks/refs_issues_diffs_calculator.go
  plugins/refdiff/tasks/refs_pr_cherry_pick_calculator.go
Labels: type/bug-fix

#1635 `fix`: open blueprint dialog on automation toggle
  config-ui/src/hooks/useBlueprintManager.jsx
  config-ui/src/pages/blueprints/index.jsx
  config-ui/src/pages/pipelines/create.jsx
Labels: enhancement, type/bug-fix

#1623 `fix`: fetch gitextractor github repos from domain layer api
  config-ui/src/components/pipelines/ProviderSettings.jsx
  config-ui/src/hooks/useConnectionManager.jsx
  config-ui/src/pages/pipelines/create.jsx
Labels: enhancement, type/bug-fix

#1627 `fix`: create pipeline: auto-close blueprint dialog on save
  config-ui/src/pages/pipelines/create.jsx
Labels: enhancement, type/bug-fix

#1639 `fix`: config-ui: connections - update active connection state after modify
  config-ui/src/hooks/useConnectionManager.jsx
  config-ui/src/hooks/useSettingsManager.jsx
Labels: priority/high, type/bug-fix

#1640 `fix`: config-ui: hide triggers legacy feature on sidebar menu
  config-ui/src/components/Sidebar/MenuConfiguration.jsx
Labels: enhancement, type/bug-fix

#1612 fix: all pipelines triggered by different blueprints have same name
  services/blueprint.go
Labels: type/bug-fix

#1643 `fix`: blueprints: update cron preset frequency options + fixes
  config-ui/src/components/blueprints/AddBlueprintDialog.jsx
  config-ui/src/hooks/useBlueprintManager.jsx
  config-ui/src/pages/blueprints/index.jsx
  config-ui/src/pages/pipelines/activity.jsx
  config-ui/src/pages/pipelines/create.jsx
  config-ui/src/pages/pipelines/index.jsx
Labels: type/bug-fix

#1647 `fix`: blueprints: refactor cron expression parsing
  config-ui/package-lock.json
  config-ui/package.json
  config-ui/src/components/blueprints/AddBlueprintDialog.jsx
  config-ui/src/components/blueprints/BlueprintsGrid.jsx
  config-ui/src/components/pipelines/ProviderSettings.jsx
  config-ui/src/hooks/useBlueprintManager.jsx
  config-ui/src/hooks/useBlueprintValidation.jsx
  config-ui/src/hooks/useConnectionManager.jsx
  config-ui/src/pages/blueprints/index.jsx
  config-ui/src/pages/configure/integration/manage.jsx
  config-ui/src/pages/pipelines/create.jsx
Labels: enhancement, priority/high, type/bug-fix

#1697 `feat` `v0.10.0` connection inputs: add validate-on-focus support
  config-ui/src/components/validation/InputValidationError.jsx
  config-ui/src/pages/configure/connections/ConnectionForm.jsx
Labels: enhancement, component/config-ui

#1694 `fix` `v0.10.0` jira provider - remove duplicate jira issue types from list
  config-ui/src/hooks/useJIRA.jsx
Labels: type/bug-fix, component/config-ui

#1732 docs: update link of pipeline-advanced-mode
  README.md
Labels: type/docs

#1735 fix: jira test connection api
  plugins/jira/api/connection.go
Labels: type/bug-fix

#1756 fix: config-ui - use slack as primary contact (navlink icon)
  config-ui/src/components/Nav.jsx
  config-ui/src/images/slack-mark-monochrome-black.svg
  config-ui/src/images/slack-rgb.svg
  config-ui/src/styles/nav.scss
Labels: type/bug-fix, component/config-ui

#1769 feat: config ui - add devlake api version tag to sidebar
  config-ui/src/components/Sidebar.jsx
Labels: enhancement, component/config-ui
