Repository apache/incubator-devlake, pull requests merged in 2022-05, with the labels that each got.

#1782 docs: update demo link
  README.md
Labels: type/docs

#1757 feat: config-ui - register dbt and ae as pipeline providers
  config-ui/src/components/menus/PipelineConfigsMenu.jsx
  config-ui/src/components/pipelines/TaskActivity.jsx
  config-ui/src/data/Providers.js
  config-ui/src/data/pipeline-config-samples/dbt.js
  config-ui/src/hooks/usePipelineManager.jsx
  config-ui/src/hooks/usePipelineValidation.jsx
  config-ui/src/images/ae.png
  config-ui/src/images/dbt.png
  config-ui/src/pages/pipelines/activity.jsx
Labels: enhancement, component/config-ui

#1742 docs: update k8s deployment
  README.md
  config/config.go
  k8s-deploy.yaml
Labels: type/docs

#1789 feat: embed piechart into grafana image
  docker-compose-temporal.yml
  docker-compose.yml
  grafana/Dockerfile
  k8s-deploy.yaml
Labels: type/feature-development

#1793 fix(tapd): remove unsupported tag in gorm tag for pg
  plugins/tapd/models/bug.go
  plugins/tapd/models/bug_changelog.go
  plugins/tapd/models/bug_commit.go
  plugins/tapd/models/issue.go
  plugins/tapd/models/iteration.go
  plugins/tapd/models/migrationscripts/archived/bug.go
  plugins/tapd/models/migrationscripts/archived/bug_changelog.go
  plugins/tapd/models/migrationscripts/archived/bug_commit.go
  plugins/tapd/models/migrationscripts/archived/issue.go
  plugins/tapd/models/migrationscripts/archived/iteration.go
  plugins/tapd/models/migrationscripts/archived/story.go
  plugins/tapd/models/migrationscripts/archived/story_changelog.go
  plugins/tapd/models/migrationscripts/archived/story_commits.go
  plugins/tapd/models/migrationscripts/archived/task.go
  plugins/tapd/models/migrationscripts/archived/task_changelog.go
  plugins/tapd/models/migrationscripts/archived/task_commits.go
  plugins/tapd/models/migrationscripts/archived/user.go
  plugins/tapd/models/migrationscripts/archived/worklog.go
  plugins/tapd/models/migrationscripts/archived/workspace.go
  plugins/tapd/models/story.go
  plugins/tapd/models/story_changelog.go
  plugins/tapd/models/story_commits.go
  plugins/tapd/models/task.go
  plugins/tapd/models/task_changelog.go
  plugins/tapd/models/task_commits.go
  plugins/tapd/models/user.go
  plugins/tapd/models/worklog.go
  plugins/tapd/models/workspace.go
  plugins/tapd/tasks/bug_changelog_converter.go
  plugins/tapd/tasks/story_changelog_converter.go
  plugins/tapd/tasks/task_changelog_converter.go
Labels: type/bug-fix

#1794 refactor(framework): rename pipeline.step to stage
  models/migrationscripts/register.go
  models/migrationscripts/updateSchemas20220505.go
  models/pipeline.go
  runner/run_pipeline.go
Labels: type/refactor

#1818 fix(jira): change subtask name `ConvertUsers` to `convertUsers`
  plugins/jira/jira.go
Labels: type/bug-fix, breaking

#1814 feat(github): change invalid `token` index
  plugins/github/api/connection.go
Labels: type/feature-request

#1785 fix: use multi-line textarea on github token field
  config-ui/src/data/Providers.js
  config-ui/src/pages/configure/connections/ConnectionForm.jsx
  config-ui/src/styles/common.scss
  config-ui/src/styles/integration.scss
Labels: enhancement, type/bug-fix, component/config-ui

#1808 1717 config UI
  config-ui/cypress/integration/0-api/api.spec.js
  config-ui/src/hooks/useConnectionManager.jsx
  config-ui/src/hooks/useSettingsManager.jsx
  config-ui/src/pages/configure/settings/github.jsx
Labels: breaking

#1819 fix(github): change `author_id` to bigint
  docker-compose.yml
  plugins/github/github.go
  plugins/github/models/migrationscripts/updateSchemas20220509.go
Labels: type/bug-fix

#1836 fix(gitlab): sql not supported by pg
  models/domainlayer/code/note.go
  models/migrationscripts/register.go
  models/migrationscripts/updateSchemas20220510.go
  plugins/gitlab/gitlab.go
  plugins/gitlab/models/migrationscripts/updateSchemas20220510.go
  plugins/gitlab/models/mr_note.go
  plugins/gitlab/tasks/mr_enricher.go
  plugins/gitlab/tasks/mr_note_extractor.go
  plugins/gitlab/tasks/note_convertor.go
Labels: type/bug-fix, breaking

#1838 fix: system panic when http response code is 503
  plugins/helper/api_async_client.go
  plugins/helper/api_async_client_test.go
  plugins/helper/api_collector_test.go
Labels: type/bug-fix

#1832 fix: pipeline activity - add subtask progress details
  config-ui/src/components/pipelines/TaskActivity.jsx
  config-ui/src/images/infinity-2.png
Labels: enhancement, type/bug-fix, component/config-ui

#1859 fix(config-ui): change Username/Password to camelCase
  config-ui/src/hooks/useConnectionManager.jsx
Labels: type/bug-fix

#1894 docs: update architecture diagram
  ARCHITECTURE.md
  docs/v0.11-arch-component.svg
  docs/v0.11-arch-dataflow.svg
Labels: type/docs
