Repository apache/incubator-devlake, pull requests merged in 2023-04, with the labels that each got.

#4839 CI/Tests: Optimize GitHub workflows tests performance
  .github/workflows/test-e2e.yml
  backend/Makefile
  backend/core/migration/migrator.go
  backend/test/Readme.md
  backend/test/e2e/api/task/task_test.go
  backend/test/e2e/remote/docker-compose.test.yml
  backend/test/e2e/remote/helper.go
  backend/test/e2e/remote/python_plugin_test.go
  backend/test/e2e/services/pipeline_runner_test.go
  backend/test/e2e/services/server_startup_test.go
  backend/test/helper/api.go
  backend/test/helper/bootstrap.go
  backend/test/helper/client.go
  backend/test/helper/client_factory.go
  backend/test/helper/db_selector.go
  backend/test/helper/init.go
  backend/test/helper/json_helper.go
  backend/test/helper/models.go
  backend/test/helper/utils.go
  backend/test/init.go
Labels: devops, component/testing

#4831 Fix Azuredevops UI pipeline run
  backend/python/plugins/azuredevops/azuredevops/main.py
  backend/python/plugins/azuredevops/azuredevops/models.py
  backend/python/plugins/azuredevops/azuredevops/streams/builds.py
  backend/python/plugins/azuredevops/azuredevops/streams/jobs.py
  backend/python/plugins/azuredevops/tests/streams_test.py
  backend/python/pydevlake/pydevlake/api.py
  backend/python/pydevlake/pydevlake/context.py
  backend/python/pydevlake/pydevlake/ipc.py
  backend/python/pydevlake/pydevlake/message.py
  backend/python/pydevlake/pydevlake/model.py
  backend/python/pydevlake/pydevlake/plugin.py
  backend/python/pydevlake/pydevlake/subtasks.py
  backend/python/pydevlake/pydevlake/testing/testing.py
  backend/python/pydevlake/tests/stream_test.py
  backend/python/test/fakeplugin/fakeplugin/main.py
  backend/server/services/remote/models/dynamic_domain_scopes.go
  backend/server/services/remote/models/models.go
  backend/server/services/remote/plugin/plugin_extensions.go
  backend/test/e2e/remote/helper.go
  backend/test/e2e/remote/python_plugin_test.go
Labels: component/plugins, pr-type/bug-fix, component/framework

#4636 refactor: Rename state table used by Singer framework
  backend/core/models/migrationscripts/20230405_rename_tap_collector_state.go
  backend/core/models/migrationscripts/register.go
  backend/helpers/pluginhelper/tap/models.go
Labels: priority/low, component/framework

#4848 cherrypick(config-ui): update the parameter tagsOrder to tagsLimit
  config-ui/src/plugins/register/bitbucket/config.tsx
  config-ui/src/plugins/register/bitbucket/transformation.tsx
  config-ui/src/plugins/register/github/config.tsx
  config-ui/src/plugins/register/github/transformation.tsx
Labels: cherrypick

#4874 [fix-4872]: Fix scopes API path in PagerDuty
  backend/helpers/pluginhelper/api/scope_helper.go
  backend/plugins/pagerduty/api/scope.go
  backend/plugins/pagerduty/impl/impl.go
Labels: component/plugins

#4916 Rename CiCDPipelineCommit.repo to repo_url
  backend/python/plugins/azuredevops/azuredevops/streams/builds.py
  backend/python/plugins/azuredevops/tests/streams_test.py
  backend/python/pydevlake/pydevlake/domain_layer/devops.py
Labels: component/plugins, component/framework

#4973 fix: Fix wrong package name in domain ids
  backend/server/services/remote/plugin/plugin_impl.go
Labels: component/plugins, component/framework

#4974 fix: monthly cfr in DORA dashboard
  grafana/dashboards/DORA.json
Labels: needs-cherrypick
