Repository apache/incubator-devlake, pull requests merged in 2023-09, with the labels that each got.

#6004 cherry-pick fix(zentao): get all tasks ignore task's status
  backend/plugins/zentao/tasks/task_collector.go
Labels: cherrypick

#6016 cherry-pick fix(zentao): keep issue_repo_commits.issue_id the same with issues.id
  backend/plugins/zentao/e2e/snapshot_tables/issue_bug_repo_commits.csv
  backend/plugins/zentao/e2e/snapshot_tables/issue_story_repo_commits.csv
  backend/plugins/zentao/e2e/snapshot_tables/issue_task_repo_commits.csv
  backend/plugins/zentao/tasks/bug_repo_commits_convertor.go
  backend/plugins/zentao/tasks/story_repo_commits_convertor.go
  backend/plugins/zentao/tasks/task_repo_commits_convertor.go
Labels: cherrypick

#6017 cherry-pick fix(zentao): keep issue_repo_commits.issue_id the same with issues.id
  backend/plugins/zentao/e2e/snapshot_tables/issue_bug_repo_commits.csv
  backend/plugins/zentao/e2e/snapshot_tables/issue_story_repo_commits.csv
  backend/plugins/zentao/e2e/snapshot_tables/issue_task_repo_commits.csv
  backend/plugins/zentao/tasks/bug_repo_commits_convertor.go
  backend/plugins/zentao/tasks/story_repo_commits_convertor.go
  backend/plugins/zentao/tasks/task_repo_commits_convertor.go
Labels: cherrypick

#6036 fix: update opened date and status is nil logic
  backend/plugins/zentao/e2e/execution_test.go
  backend/plugins/zentao/e2e/raw_tables/_raw_zentao_api_executions.csv
  backend/plugins/zentao/e2e/snapshot_tables/_tool_zentao_executions.csv
  backend/plugins/zentao/e2e/snapshot_tables/execution_board_sprint.csv
  backend/plugins/zentao/e2e/snapshot_tables/execution_sprint.csv
  backend/plugins/zentao/tasks/execution_convertor.go
Labels: needs-cherrypick-v0.18

#6046 fix(jenkins): unable to collect jobs nested in folder (v0.19-beta2)
  backend/plugins/jenkins/api/jobs.go
Labels: needs-cherrypick-v0.18

#6049 fix: update started_date logic
  backend/plugins/zentao/e2e/snapshot_tables/execution_sprint.csv
  backend/plugins/zentao/tasks/execution_convertor.go
Labels: needs-cherrypick-v0.18

#6050 feat(webhook): plugin webhook's detail and list api can get api key info now
  backend/core/models/api_key.go
  backend/helpers/apikeyhelper/apikeyhelper.go
  backend/plugins/webhook/api/connection.go
  backend/plugins/webhook/api/init.go
  backend/plugins/webhook/models/connection.go
  backend/server/services/apikeys.go
Labels: needs-cherrypick-v0.19

#6057 cherry-pick fix(zentao): fix null started_date fields in sprints table
  backend/plugins/zentao/e2e/snapshot_tables/execution_sprint.csv
  backend/plugins/zentao/tasks/execution_convertor.go
Labels: cherrypick

#6058 cherry-pick fix(zentao): fix null started_date fields in sprints table
  backend/plugins/zentao/e2e/snapshot_tables/execution_sprint.csv
  backend/plugins/zentao/tasks/execution_convertor.go
Labels: cherrypick

#6065 fix(zentao): remove unused change field
  backend/plugins/zentao/models/bug_commits.go
  backend/plugins/zentao/models/story_commits.go
  backend/plugins/zentao/models/task_commits.go
Labels: cherrypick-completed, needs-cherrypick-v0.18, needs-cherrypick-v0.19

#6071 fix(zentao): update zentao project's progres field's type, make it mo…
  backend/plugins/zentao/api/init.go
  backend/plugins/zentao/api/remote.go
  backend/plugins/zentao/models/project.go
Labels: needs-cherrypick-v0.18, needs-cherrypick-v0.19

#6076 build image on pr merged and pr with specific label
  .github/workflows/build.yml
Labels: envtest

#6089 fix(zentao): fix progress field when configurating scopes
  backend/plugins/zentao/models/project.go
Labels: cherrypick-completed, needs-cherrypick-v0.18, needs-cherrypick-v0.19

#6096 [bamboo] fix #6082
  backend/plugins/bamboo/tasks/job_build_convertor.go
Labels: needs-cherrypick-v0.19

#6118 cherry-pick fix(zentao): process tasks' children when collecting data instead of extracting data to v0.19
  backend/plugins/zentao/models/task.go
  backend/plugins/zentao/tasks/task_collector.go
  backend/plugins/zentao/tasks/task_collector_test.go
  backend/plugins/zentao/tasks/task_extractor.go
Labels: cherrypick

#6121 cherry-pick [bamboo] fix cicd_scope.url field to v0.19
  backend/plugins/bamboo/e2e/snapshot_tables/cicd_scopes.csv
  backend/plugins/bamboo/tasks/plan_convertor.go
  backend/plugins/bamboo/tasks/shared.go
  backend/plugins/bamboo/tasks/shared_test.go
Labels: cherrypick

#6120 cherry-pick [bamboo] fix #6082 to v0.19
  backend/plugins/bamboo/tasks/job_build_convertor.go
Labels: cherrypick

#6122 fix(bamboo): rename raw tables if they exist
  backend/plugins/bamboo/models/migrationscripts/20230920_rename_raw_tables.go
  backend/plugins/bamboo/models/migrationscripts/register.go
Labels: needs-cherrypick-v0.19

#6123 cherry-pick fix(bamboo): rename raw tables if they exist to v0.19
  backend/plugins/bamboo/models/migrationscripts/20230920_rename_raw_tables.go
  backend/plugins/bamboo/models/migrationscripts/register.go
Labels: cherrypick

#6130 fix(bamboo): update migration script's name, avoid runtime error
  backend/core/models/migrationscripts/20230831_add_cicd_deployments_table.go
  backend/plugins/bamboo/models/migrationscripts/20230920_rename_raw_tables.go
Labels: pr-type/bug-fix

#6131 cherry-pick fix(bamboo): update migration script's name, avoid runtime error to v0.19
  backend/plugins/bamboo/models/migrationscripts/20230920_rename_raw_tables.go
Labels: cherrypick

#6133 fix(bamboo): update cicd_scopes, cicd_pipelines and cicd_deployment_commits tables' name field
  backend/plugins/bamboo/e2e/deploy_build_test.go
  backend/plugins/bamboo/e2e/snapshot_tables/cicd_deployment_commits.csv
  backend/plugins/bamboo/e2e/snapshot_tables/cicd_pipelines.csv
  backend/plugins/bamboo/models/plan_build.go
  backend/plugins/bamboo/tasks/deploy_build_convertor.go
  backend/plugins/bamboo/tasks/plan_build_convertor.go
Labels: needs-cherrypick-v0.19

#6141 fix(bamboo): set domain layer's repo_url field with an acceptable value
  backend/plugins/bamboo/e2e/deploy_build_test.go
  backend/plugins/bamboo/e2e/deploy_test.go
  backend/plugins/bamboo/e2e/job_build_test.go
  backend/plugins/bamboo/e2e/job_test.go
  backend/plugins/bamboo/e2e/plan_build_commits_test.go
  backend/plugins/bamboo/e2e/plan_build_test.go
  backend/plugins/bamboo/e2e/plan_test.go
  backend/plugins/bamboo/e2e/snapshot_tables/cicd_deployment_commits.csv
  backend/plugins/bamboo/e2e/snapshot_tables/cicd_pipeline_commits.csv
  backend/plugins/bamboo/tasks/deploy_build_convertor.go
  backend/plugins/bamboo/tasks/plan_commit_convertor.go
  backend/plugins/bamboo/tasks/shared.go
  backend/plugins/bamboo/tasks/shared_test.go
Labels: type/bug, needs-cherrypick-v0.19

#6163 fix: gitlab projects search api
  backend/plugins/gitlab/api/remote.go
Labels: needs-cherrypick-v0.19

#6170 cherry-pick fix(bamboo): update cicd_scopes, cicd_pipelines and cicd_deployment_commits tables' name field to v0.19
  backend/plugins/bamboo/e2e/deploy_build_test.go
  backend/plugins/bamboo/e2e/snapshot_tables/cicd_deployment_commits.csv
  backend/plugins/bamboo/e2e/snapshot_tables/cicd_pipelines.csv
  backend/plugins/bamboo/models/plan_build.go
  backend/plugins/bamboo/tasks/deploy_build_convertor.go
  backend/plugins/bamboo/tasks/plan_build_convertor.go
Labels: cherrypick

#6171 cherry-pick fix(bamboo): set domain layer's repo_url field with an acceptable value to v0.19
  backend/plugins/bamboo/e2e/deploy_build_test.go
  backend/plugins/bamboo/e2e/deploy_test.go
  backend/plugins/bamboo/e2e/job_build_test.go
  backend/plugins/bamboo/e2e/job_test.go
  backend/plugins/bamboo/e2e/plan_build_commits_test.go
  backend/plugins/bamboo/e2e/plan_build_test.go
  backend/plugins/bamboo/e2e/plan_test.go
  backend/plugins/bamboo/e2e/snapshot_tables/cicd_deployment_commits.csv
  backend/plugins/bamboo/e2e/snapshot_tables/cicd_pipeline_commits.csv
  backend/plugins/bamboo/tasks/deploy_build_convertor.go
  backend/plugins/bamboo/tasks/plan_commit_convertor.go
  backend/plugins/bamboo/tasks/shared.go
  backend/plugins/bamboo/tasks/shared_test.go
Labels: cherrypick
