Repository apache/incubator-devlake, pull requests merged in 2023-12, with the labels that each got.

#6546 refactor: gitlab adopts new remote api helper
  backend/helpers/pluginhelper/api/ds_remote_api_scope_list_helper.go
  backend/plugins/github/api/remote.go
  backend/plugins/gitlab/api/init.go
  backend/plugins/gitlab/api/proxy.go
  backend/plugins/gitlab/api/remote.go
  backend/plugins/gitlab/models/connection.go
  backend/plugins/gitlab/models/project.go
Labels: breaking-change

#6565 fix(azure): remove sensitive tokens in api resp
  backend/helpers/pluginhelper/api/connection_helper.go
  backend/server/services/remote/plugin/connection_api.go
  backend/test/e2e/remote/helper.go
  backend/test/e2e/remote/python_plugin_test.go
Labels: pr-type/feature-development

#6566 fix(plan): no entities specified, use all entities enabled by default
  backend/plugins/github/api/blueprint_v200.go
Labels: needs-cherrypick-v0.20

#6581 refactor: added CreateAndRunApiServer
  backend/server/api/api.go
  backend/server/main.go
  backend/test/helper/client.go
Labels: needs-cherrypick-v0.20

#6587 fix: incorrect datetime value: '0000-00-00' for column latest_updated
  backend/plugins/github/models/deployment.go
  backend/plugins/github_graphql/tasks/deployment_collector.go
  backend/plugins/github_graphql/tasks/deployment_extractor.go
Labels: needs-cherrypick-v0.20

#6585 fix: option time after for plugins
  backend/helpers/pluginhelper/api/api_collector_with_state.go
  backend/plugins/ae/tasks/task_data.go
  backend/plugins/bamboo/models/task.go
  backend/plugins/bitbucket/api/blueprint_V200_test.go
  backend/plugins/bitbucket/tasks/task_data.go
  backend/plugins/circleci/tasks/task_data.go
  backend/plugins/customize/tasks/task_data.go
  backend/plugins/feishu/tasks/task_data.go
  backend/plugins/gitee/tasks/task_data.go
  backend/plugins/github/tasks/task_data.go
  backend/plugins/gitlab/tasks/task_data.go
  backend/plugins/icla/tasks/task_data.go
  backend/plugins/jenkins/tasks/task_data.go
  backend/plugins/jira/tasks/task_data.go
  backend/plugins/opsgenie/tasks/task_data.go
  backend/plugins/pagerduty/tasks/task_data.go
  backend/plugins/slack/tasks/task_data.go
  backend/plugins/sonarqube/tasks/task_data.go
  backend/plugins/tapd/tasks/task_data.go
  backend/plugins/teambition/tasks/task_data.go
  backend/plugins/trello/tasks/task_data.go
  backend/plugins/zentao/api/blueprint_V200_test.go
  backend/plugins/zentao/tasks/task_data.go
Labels: needs-cherrypick-v0.20

#6601 fix: github grapahql increment collector
  backend/helpers/pluginhelper/api/api_collector_with_state.go
  backend/plugins/github_graphql/tasks/deployment_collector.go
  backend/plugins/github_graphql/tasks/issue_collector.go
  backend/plugins/github_graphql/tasks/pr_collector.go
Labels: needs-cherrypick-v0.20

#6600 fix(config-ui): wrong default value
  config-ui/src/pages/blueprint/detail/components/sync-policy/index.tsx
Labels: needs-cherrypick-v0.20

#6633 fix(db): upgrade gorm to v1.25.5
  backend/core/runner/db.go
  backend/go.mod
  backend/go.sum
Labels: pr-type/bug-fix, needs-cherrypick-v0.20

#6649 fix(zentao): fix panic when checking db connections
  backend/core/runner/db.go
  backend/go.mod
Labels: pr-type/bug-fix, needs-cherrypick-v0.20

#6657 fix: bp trigger swag
  backend/server/api/blueprints/blueprints.go
Labels: needs-cherrypick-v0.20

#6663 fix: collect all data when timeafter is nil
  backend/helpers/pluginhelper/api/api_collector_with_state.go
Labels: needs-cherrypick-v0.20

#6660 fix: gitextractor can not run
  backend/plugins/github/api/blueprint_v200.go
  backend/plugins/gitlab/api/blueprint_v200.go
Labels: needs-cherrypick-v0.20

#6679 fix: type trans rules
  backend/plugins/gitee/tasks/issue_extractor.go
  backend/plugins/gitee/tasks/pr_extractor.go
  backend/plugins/github/e2e/snapshot_tables/_tool_github_issues.csv
  backend/plugins/github/tasks/issue_extractor.go
  backend/plugins/github/tasks/pr_extractor.go
  backend/plugins/github_graphql/tasks/issue_extractor.go
  backend/plugins/github_graphql/tasks/pr_extractor.go
  backend/plugins/gitlab/tasks/issue_extractor.go
  backend/plugins/gitlab/tasks/mr_detail_extractor.go
  backend/plugins/gitlab/tasks/mr_extractor.go
Labels: needs-cherrypick-v0.20

#6688 fix: duration_sec has wrong value
  backend/plugins/gitlab/e2e/pipelines_detail_test.go
  backend/plugins/gitlab/e2e/pipelines_test.go
  backend/plugins/gitlab/e2e/raw_tables/_raw_gitlab_api_pipeline_details.csv
  backend/plugins/gitlab/e2e/snapshot_tables/_tool_gitlab_pipelines.csv
  backend/plugins/gitlab/e2e/snapshot_tables/cicd_pipeline_commits.csv
  backend/plugins/gitlab/e2e/snapshot_tables/cicd_pipelines.csv
  backend/plugins/gitlab/models/migrationscripts/20231221_add_time_filed_to_pipeline_projects.go
  backend/plugins/gitlab/models/migrationscripts/register.go
  backend/plugins/gitlab/models/pipeline.go
  backend/plugins/gitlab/tasks/pipeline_detail_collector.go
  backend/plugins/gitlab/tasks/pipeline_detail_extractor.go
  backend/plugins/gitlab/tasks/pipeline_extractor.go
Labels: needs-cherrypick-v0.20

#6698 fix(dora): add deployment generator
  backend/plugins/bamboo/e2e/deploy_build_test.go
  backend/plugins/bamboo/impl/impl.go
  backend/plugins/bamboo/tasks/deploy_build_to_deployment_commit_convertor.go
  backend/plugins/bamboo/tasks/deploy_build_to_deployment_convertor.go
  backend/plugins/bitbucket/tasks/deployment_convertor.go
  backend/plugins/dora/impl/impl.go
  backend/plugins/dora/impl/impl_test.go
  backend/plugins/dora/tasks/deployment_commits_generator.go
  backend/plugins/dora/tasks/deployment_generator.go
  backend/plugins/github/tasks/deployment_convertor.go
  backend/plugins/gitlab/tasks/deployment_convertor.go
Labels: pr-type/bug-fix, needs-cherrypick-v0.20

#6703 cherry pick #6698 fix(dora): add deployment generator to v0.20
  backend/plugins/bamboo/e2e/deploy_build_test.go
  backend/plugins/bamboo/impl/impl.go
  backend/plugins/bamboo/tasks/deploy_build_to_deployment_commit_convertor.go
  backend/plugins/bamboo/tasks/deploy_build_to_deployment_convertor.go
  backend/plugins/bitbucket/tasks/deployment_convertor.go
  backend/plugins/dora/impl/impl.go
  backend/plugins/dora/impl/impl_test.go
  backend/plugins/dora/tasks/deployment_commits_generator.go
  backend/plugins/dora/tasks/deployment_generator.go
  backend/plugins/github/tasks/deployment_convertor.go
  backend/plugins/gitlab/tasks/deployment_convertor.go
Labels: cherrypick
