Repository apache/incubator-devlake, pull requests merged in 2023-05, with the labels that each got.

#5078 fix: Correct Swagger spec template path discovery
  backend/Dockerfile
  backend/core/config/config_viper.go
  backend/resources/swagger/open_api_spec.json.tmpl
  backend/server/services/remote/plugin/doc/open_api.go
Labels: pr-type/bug-fix

#5150 fix: Jenkins Build Success Rate Graph disordered
  grafana/dashboards/Jenkins.json
Labels: pr-type/bug-fix

#5172 fix: update DORA validation dashboard
  grafana/dashboards/DORA DEBUG.json
  grafana/dashboards/DORA.json
  grafana/dashboards/DORADebug.json
Labels: needs-cherrypick-v0.17

#5196 [fix-5107]: PagerDuty data collection limit with service filtering
  backend/helpers/pluginhelper/api/api_async_client.go
  backend/plugins/pagerduty/tasks/incidents_collector.go
Labels: pr-type/bug-fix, needs-cherrypick-v0.17

#5229 [fix-5233]: Pagerduty MTTR computation fix
  backend/plugins/pagerduty/impl/impl.go
  backend/plugins/pagerduty/tasks/incidents_converter.go
  backend/plugins/pagerduty/tasks/service_converter.go
Labels: pr-type/bug-fix, needs-cherrypick-v0.17

#5281 [fix-5278]: PagerDuty incident conversion query by service ID
  backend/plugins/pagerduty/api/remote.go
  backend/plugins/pagerduty/models/raw/incidents.go
  backend/plugins/pagerduty/models/raw/services.go
  backend/plugins/pagerduty/tasks/incidents_converter.go
  backend/plugins/pagerduty/tasks/incidents_extractor.go
Labels: pr-type/bug-fix, needs-cherrypick-v0.17

#5287 cherrypick(v0.17.0-beta7): #5278
  backend/plugins/pagerduty/api/remote.go
  backend/plugins/pagerduty/models/raw/incidents.go
  backend/plugins/pagerduty/models/raw/services.go
  backend/plugins/pagerduty/tasks/incidents_converter.go
  backend/plugins/pagerduty/tasks/incidents_extractor.go
Labels: cherrypick

#5290 [feat-5277]: Delete Scopes support for all plugins
  backend/helpers/pluginhelper/api/scope_generic_helper.go
  backend/helpers/pluginhelper/api/scope_helper.go
  backend/helpers/pluginhelper/api/scope_helper_test.go
  backend/plugins/bamboo/api/init.go
  backend/plugins/bamboo/api/scope.go
  backend/plugins/bamboo/impl/impl.go
  backend/plugins/bitbucket/api/init.go
  backend/plugins/bitbucket/api/scope.go
  backend/plugins/bitbucket/impl/impl.go
  backend/plugins/github/api/init.go
  backend/plugins/github/api/scope.go
  backend/plugins/github/impl/impl.go
  backend/plugins/gitlab/api/init.go
  backend/plugins/gitlab/api/scope.go
  backend/plugins/gitlab/impl/impl.go
  backend/plugins/jenkins/api/init.go
  backend/plugins/jenkins/api/scope.go
  backend/plugins/jenkins/impl/impl.go
  backend/plugins/jira/api/init.go
  backend/plugins/jira/api/scope.go
  backend/plugins/jira/impl/impl.go
  backend/plugins/pagerduty/api/init.go
  backend/plugins/pagerduty/api/scope.go
  backend/plugins/sonarqube/api/init.go
  backend/plugins/sonarqube/api/scope.go
  backend/plugins/sonarqube/impl/impl.go
  backend/plugins/tapd/api/init.go
  backend/plugins/tapd/api/scope.go
  backend/plugins/tapd/impl/impl.go
  backend/plugins/trello/api/scope.go
  backend/plugins/trello/impl/impl.go
  backend/plugins/zentao/api/init.go
  backend/plugins/zentao/api/scope.go
  backend/plugins/zentao/impl/impl.go
  backend/server/services/remote/plugin/scope_api.go
Labels: component/framework

#5289 [feat-4864]: Backend support for project deletion
  backend/helpers/pluginhelper/api/scope_generic_helper.go
  backend/helpers/pluginhelper/api/scope_helper.go
  backend/helpers/pluginhelper/services/blueprint_helper.go
  backend/server/api/project/project.go
  backend/server/api/router.go
  backend/server/services/project.go
Labels: component/framework

#5301 cherrypick(v0.17.0-beta7): #5288 (Enable CI tests for cherry-pick PRs)
  .github/workflows/test-e2e.yml
  .github/workflows/test.yml
Labels: devops, cherrypick

#5310 Fix substream.fetch
  backend/python/plugins/azuredevops/azuredevops/main.py
  backend/python/plugins/azuredevops/azuredevops/models.py
  backend/python/pydevlake/pydevlake/subtasks.py
Labels: type/bug, needs-cherrypick-v0.17, bot/auto-cherry-pick-for-release-v0.17

#5300 Fix exception on 204 when collecting jobs
  backend/python/README.md
  backend/python/plugins/azuredevops/azuredevops/api.py
  backend/python/plugins/azuredevops/azuredevops/streams/jobs.py
  backend/python/pydevlake/pydevlake/api.py
Labels: needs-cherrypick-v0.17

#5335 cherrypick(v0.17.0-beta9): #5311
  backend/plugins/pagerduty/tasks/incidents_collector.go
  backend/plugins/pagerduty/tasks/task_data.go
Labels: pr-type/bug-fix, cherrypick
