Repository apache/incubator-devlake, pull requests merged in 2023-06, with the labels that each got.

#5337 fix: Build.result must be optional
  backend/python/plugins/azuredevops/azuredevops/models.py
Labels: needs-cherrypick-v0.17

#5346 cherrypick(v0.17.0-beta10): #5311 (missing fix)
  backend/plugins/pagerduty/e2e/raw_tables/_raw_pagerduty_incidents.csv
  backend/plugins/pagerduty/e2e/snapshot_tables/_tool_pagerduty_assignments.csv
  backend/plugins/pagerduty/e2e/snapshot_tables/_tool_pagerduty_incidents.csv
  backend/plugins/pagerduty/e2e/snapshot_tables/_tool_pagerduty_users.csv
  backend/plugins/pagerduty/tasks/incidents_collector.go
  backend/plugins/pagerduty/tasks/incidents_converter.go
  backend/plugins/pagerduty/tasks/incidents_extractor.go
  backend/plugins/pagerduty/tasks/task_data.go
Labels: pr-type/bug-fix, cherrypick

#5380 fix(Jira): Fix Jira scope reflection field name: BoardID -> BoardId
  backend/plugins/jira/api/init.go
Labels: pr-type/bug-fix

#5386 5383 build not found
  backend/python/plugins/azuredevops/azuredevops/api.py
  backend/python/plugins/azuredevops/azuredevops/streams/jobs.py
  backend/python/pydevlake/pydevlake/subtasks.py
Labels: type/bug, needs-cherrypick-v0.17

#5401 fix: missing blueprints from the scope list API
  backend/helpers/pluginhelper/api/scope_generic_helper.go
  backend/helpers/pluginhelper/services/blueprint_helper.go
Labels: pr-type/bug-fix

#5448 [fix-5085]: Azure bug fixes related to external repo support
  backend/helpers/pluginhelper/api/scope_generic_helper.go
  backend/python/plugins/azuredevops/azuredevops/main.py
  backend/python/plugins/azuredevops/azuredevops/streams/builds.py
  backend/python/pydevlake/pydevlake/testing/testing.py
  backend/server/services/remote/plugin/default_api.go
Labels: pr-type/bug-fix

#5449 fix: Add missing RawScopeParamName field to plugins
  backend/core/models/blueprint.go
  backend/helpers/pluginhelper/api/scope_generic_helper.go
  backend/helpers/pluginhelper/api/scope_helper_test.go
  backend/plugins/bamboo/api/init.go
  backend/plugins/bitbucket/api/init.go
  backend/plugins/gitlab/api/init.go
  backend/plugins/jenkins/api/init.go
  backend/plugins/jira/api/init.go
  backend/plugins/sonarqube/api/init.go
  backend/plugins/tapd/api/init.go
  backend/plugins/trello/api/init.go
  backend/plugins/zentao/api/init.go
  backend/server/services/project.go
  backend/server/services/remote/plugin/default_api.go
  backend/server/services/remote/plugin/plugin_impl.go
  backend/test/e2e/manual/azuredevops/azure_test.go
  backend/test/helper/api.go
Labels: pr-type/bug-fix

#5472 fix: Tool table discovery fix
  backend/helpers/pluginhelper/api/reflection_helper.go
  backend/helpers/pluginhelper/api/scope_generic_helper.go
  backend/server/services/remote/plugin/plugin_impl.go
Labels: pr-type/bug-fix

#5470 [fix-5453](pydevlake): Make ScopeConfig optional
  backend/python/README.md
  backend/python/plugins/azuredevops/azuredevops/main.py
  backend/python/pydevlake/pydevlake/context.py
  backend/python/pydevlake/pydevlake/ipc.py
  backend/python/pydevlake/pydevlake/model.py
  backend/python/pydevlake/pydevlake/plugin.py
  backend/python/pydevlake/pydevlake/testing/testing.py
  backend/python/pydevlake/tests/stream_test.py
  backend/server/services/remote/models/conversion.go
  backend/server/services/remote/plugin/plugin_impl.go
Labels: pr-type/bug-fix

#5504 fix: Get BlueprintsByScope APIs must account for plugin name
  backend/core/models/blueprint.go
  backend/helpers/pluginhelper/api/scope_generic_helper.go
  backend/helpers/pluginhelper/services/blueprint_helper.go
Labels: pr-type/bug-fix

#5506 [feat-5503]: Deletable scopes and connections
  backend/Makefile
  backend/core/errors/types.go
  backend/core/plugin/plugin_api.go
  backend/helpers/pluginhelper/api/connection_helper.go
  backend/helpers/pluginhelper/api/scope_generic_helper.go
  backend/helpers/pluginhelper/api/scope_helper.go
  backend/helpers/pluginhelper/services/blueprint_helper.go
  backend/plugins/ae/api/connection.go
  backend/plugins/bamboo/api/connection.go
  backend/plugins/bamboo/api/scope.go
  backend/plugins/bitbucket/api/connection.go
  backend/plugins/bitbucket/api/scope.go
  backend/plugins/feishu/api/connection.go
  backend/plugins/gitee/api/connection.go
  backend/plugins/github/api/connection.go
  backend/plugins/github/api/scope.go
  backend/plugins/gitlab/api/connection.go
  backend/plugins/gitlab/api/scope.go
  backend/plugins/jenkins/api/connection.go
  backend/plugins/jenkins/api/scope.go
  backend/plugins/jira/api/connection.go
  backend/plugins/jira/api/scope.go
  backend/plugins/pagerduty/api/connection.go
  backend/plugins/pagerduty/api/scope.go
  backend/plugins/slack/api/connection.go
  backend/plugins/sonarqube/api/connection.go
  backend/plugins/sonarqube/api/scope.go
  backend/plugins/tapd/api/connection.go
  backend/plugins/tapd/api/scope.go
  backend/plugins/teambition/api/connection.go
  backend/plugins/trello/api/connection.go
  backend/plugins/trello/api/scope.go
  backend/plugins/webhook/api/connection.go
  backend/plugins/zentao/api/connection.go
  backend/plugins/zentao/api/scope.go
  backend/python/pydevlake/pydevlake/plugin.py
  backend/server/api/router.go
  backend/server/services/project.go
  backend/server/services/remote/plugin/connection_api.go
  backend/server/services/remote/plugin/plugin_impl.go
  backend/server/services/remote/plugin/scope_api.go
  backend/test/e2e/remote/helper.go
  backend/test/e2e/remote/python_plugin_test.go
  backend/test/helper/api.go
  backend/test/helper/client.go
  backend/test/helper/client_factory.go
Labels: component/framework

#5533 fix: Scope data shouldn't be removed on deletion conflict (#5532)
  backend/helpers/pluginhelper/api/scope_generic_helper.go
  backend/test/e2e/remote/helper.go
Labels: pr-type/bug-fix

#5551 [fix-5535]: Delete scopes accurately
  .github/workflows/go-checklist.yml.bak
  backend/Makefile
  backend/core/models/dynamic_tabler.go
  backend/core/plugin/plugin_scope_abstract.go
  backend/helpers/e2ehelper/data_flow_tester.go
  backend/helpers/pluginhelper/api/api_extractor.go
  backend/helpers/pluginhelper/api/api_rawdata.go
  backend/helpers/pluginhelper/api/scope_db_helper.go
  backend/helpers/pluginhelper/api/scope_generic_helper.go
  backend/helpers/pluginhelper/api/scope_helper.go
  backend/helpers/pluginhelper/api/scope_helper_test.go
  backend/helpers/pluginhelper/csv_file_iterator.go
  backend/plugins/bamboo/models/project.go
  backend/plugins/bitbucket/models/repo.go
  backend/plugins/gitee/models/repo.go
  backend/plugins/gitee/tasks/issue_comment_extractor.go
  backend/plugins/gitee/tasks/shared.go
  backend/plugins/github/models/repo.go
  backend/plugins/github/tasks/task_data.go
  backend/plugins/gitlab/models/project.go
  backend/plugins/gitlab/tasks/account_convertor.go
  backend/plugins/gitlab/tasks/job_convertor.go
  backend/plugins/gitlab/tasks/pipeline_commit_convertor.go
  backend/plugins/gitlab/tasks/pipeline_convertor.go
  backend/plugins/gitlab/tasks/shared.go
  backend/plugins/jenkins/models/job.go
  backend/plugins/jenkins/tasks/task_data.go
  backend/plugins/jira/models/board.go
  backend/plugins/jira/tasks/task_data.go
  backend/plugins/pagerduty/models/service.go
  backend/plugins/pagerduty/tasks/task_data.go
  backend/plugins/sonarqube/impl/impl.go
  backend/plugins/sonarqube/models/sonarqube_project.go
  backend/plugins/sonarqube/tasks/shared.go
  backend/plugins/sonarqube/tasks/task_data.go
  backend/plugins/tapd/e2e/snapshot_tables/_tool_tapd_bug_statuses.csv
  backend/plugins/tapd/e2e/snapshot_tables/_tool_tapd_story_statuses.csv
  backend/plugins/tapd/models/workspace.go
  backend/plugins/tapd/tasks/account_converter.go
  backend/plugins/tapd/tasks/shared.go
  backend/plugins/tapd/tasks/workspace_converter.go
  backend/plugins/trello/models/board.go
  backend/plugins/trello/tasks/task_data.go
  backend/plugins/zentao/models/product.go
  backend/plugins/zentao/models/project.go
  backend/plugins/zentao/tasks/task_data.go
  backend/python/pydevlake/pydevlake/model.py
  backend/python/pydevlake/tests/stream_test.py
  backend/server/services/remote/models/models.go
  backend/server/services/remote/plugin/default_api.go
  backend/server/services/remote/plugin/scope_api.go
  backend/server/services/remote/plugin/scope_db_helper.go
  backend/test/e2e/remote/helper.go
Labels: pr-type/bug-fix

#5589 fix: Python now accounts for _raw_data_table for scopes
  backend/python/pydevlake/pydevlake/plugin.py
  backend/server/services/remote/plugin/plugin_extensions.go
  backend/test/e2e/remote/helper.go
Labels: pr-type/bug-fix

#5594 cherry-pick(v0.17.0-beta13): #5586
  backend/core/runner/run_task.go
Labels: cherrypick
