Repository apache/incubator-devlake, pull requests merged in 2023-11, with the labels that each got.

#6373 fix: add v0.19.0 docker compose
  devops/releases/lake-v0.19.0/docker-compose.yml
  devops/releases/lake-v0.19.0/env.example
Labels: needs-cherrypick-v0.19

#6380 fix: github apps auth can not show repos
  backend/plugins/github/api/remote.go
Labels: needs-cherrypick-v0.19

#6382 refactor(github): move deployment convertor from github_ql to github plugin
  backend/plugins/github/tasks/deployment_convertor.go
  backend/plugins/github/tasks/shared.go
  backend/plugins/github_graphql/impl/impl.go
  backend/plugins/github_graphql/tasks/deployment_collector_extractor.go
Labels: pr-type/refactor

#6392 cherry-pick fix(tapd): fix json unmarshal error #6379 to v0.19
  backend/plugins/tapd/tasks/story_status_last_step_enricher.go
Labels: cherrypick

#6395 fix(tapd): fix json unmarshal error
  backend/plugins/tapd/tasks/bug_status_last_step_enricher.go
Labels: needs-cherrypick-v0.19

#6398 update `status` and `result` fields' transformation in domain layer
  backend/core/models/domainlayer/devops/cicd_pipeline.go
  backend/plugins/bamboo/tasks/deploy_build_convertor.go
  backend/plugins/bamboo/tasks/job_build_convertor.go
  backend/plugins/bamboo/tasks/plan_build_convertor.go
  backend/plugins/bamboo/tasks/shared.go
  backend/plugins/bitbucket/e2e/snapshot_tables/cicd_pipelines.csv
  backend/plugins/bitbucket/e2e/snapshot_tables/cicd_tasks.csv
  backend/plugins/bitbucket/models/pipeline.go
  backend/plugins/bitbucket/tasks/deployment_convertor.go
  backend/plugins/bitbucket/tasks/pipeline_convertor.go
  backend/plugins/bitbucket/tasks/pipeline_steps_convertor.go
  backend/plugins/circleci/tasks/job_converter.go
  backend/plugins/circleci/tasks/workflow_converter.go
  backend/plugins/dora/e2e/deployment_generator/cicd_deployment_commits.csv
  backend/plugins/dora/e2e/deployment_generator/cicd_pipelines.csv
  backend/plugins/dora/tasks/deployment_commits_generator.go
  backend/plugins/github/e2e/snapshot_tables/cicd_pipelines.csv
  backend/plugins/github/e2e/snapshot_tables/cicd_tasks.csv
  backend/plugins/github/tasks/cicd_job_convertor.go
  backend/plugins/github/tasks/cicd_run_convertor.go
  backend/plugins/github/tasks/deployment_convertor.go
  backend/plugins/github/tasks/shared.go
  backend/plugins/gitlab/e2e/snapshot_tables/cicd_tasks.csv
  backend/plugins/gitlab/e2e/snapshot_tables/cicd_tasks_no_prod_regex.csv
  backend/plugins/gitlab/tasks/deployment_convertor.go
  backend/plugins/gitlab/tasks/job_convertor.go
  backend/plugins/gitlab/tasks/pipeline_convertor.go
  backend/plugins/gitlab/tasks/shared.go
  backend/plugins/jenkins/e2e/snapshot_tables/cicd_tasks_after_stages.csv
  backend/plugins/jenkins/tasks/build_cicd_convertor.go
  backend/plugins/jenkins/tasks/shared.go
  backend/plugins/jenkins/tasks/stage_convertor.go
Labels: pr-type/refactor

#6402 cherry-pick fix(bitbucket): fix wrong create_date in pull_request_comments to v0.19
  backend/plugins/bitbucket/tasks/pr_comment_convertor.go
Labels: cherrypick

#6403 cherry-pick fix(bamboo): fix cicd_deployment_commits.id, remove PlanResultKey from primary key list from BambooDeployBuild to v0.19
  backend/core/dal/dal.go
  backend/plugins/bamboo/e2e/snapshot_tables/cicd_deployment_commits.csv
  backend/plugins/bamboo/models/deploy_build.go
  backend/plugins/bamboo/tasks/deploy_build_convertor.go
Labels: cherrypick

#6404 fix: some license issues
  LICENSE
  config-ui/.yarn/releases/yarn-3.4.1.cjs
Labels: needs-cherrypick-v0.19

#6432 fix: zentao repo url parse error
  backend/plugins/zentao/tasks/bug_commits_extractor.go
  backend/plugins/zentao/tasks/story_commits_extractor.go
  backend/plugins/zentao/tasks/task_commits_extractor.go
Labels: needs-cherrypick-v0.19

#6335 fix(org): save project mappings in small batch
  backend/plugins/org/tasks/project_mapping.go
Labels: pr-type/bug-fix

#6443 [fix-6401/6244]: Prevent oversized payloads from Python's RemoteScopes API
  backend/go.mod
  backend/go.sum
  backend/python/pydevlake/pydevlake/ipc.py
  backend/python/pydevlake/pydevlake/plugin.py
  backend/server/services/remote/plugin/remote_scope_api.go
Labels: type/bug

#6452 docs: page and pageSize should not be required
  backend/scripts/build-plugins.sh
  backend/server/api/apikeys/apikeys.go
  backend/server/api/project/project.go
Labels: needs-cherrypick-v0.20

#6459 fix: close #6456
  grafana/Dockerfile
Labels: needs-cherrypick-v0.19, needs-cherrypick-v0.20

#6461 cherry-pic #6459 upgrade grafana to v0.20
  grafana/Dockerfile
Labels: cherrypick

#6462 fix: jenkins stages durationMillis<0
  backend/plugins/jenkins/e2e/stages_test.go
  backend/plugins/jenkins/tasks/stage_convertor.go
Labels: needs-cherrypick-v0.19

#6471 fix(config-ui): show error when initializing connection error
  config-ui/src/features/connections/slice.ts
  config-ui/src/routes/layout/layout.tsx
Labels: needs-cherrypick-v0.20

#6465 Change the type of `duration_sec` from int to float
  backend/core/models/domainlayer/devops/cicd_deployment.go
  backend/core/models/domainlayer/devops/cicd_deployment_commit.go
  backend/core/models/domainlayer/devops/cicd_pipeline.go
  backend/core/models/domainlayer/devops/cicd_task.go
  backend/core/models/migrationscripts/20220905_modify_cicd_pipeline.go
  backend/core/models/migrationscripts/20220908_modify_cicd_tasks.go
  backend/core/models/migrationscripts/20221109_modify_commits_diffs.go
  backend/core/models/migrationscripts/20231115_change_duration_sec_to_float64.go
  backend/core/models/migrationscripts/register.go
  backend/go.mod
  backend/go.sum
  backend/plugins/bamboo/tasks/deploy_build_convertor.go
  backend/plugins/bamboo/tasks/job_build_convertor.go
  backend/plugins/bamboo/tasks/plan_build_convertor.go
  backend/plugins/bitbucket/tasks/deployment_convertor.go
  backend/plugins/bitbucket/tasks/pipeline_convertor.go
  backend/plugins/bitbucket/tasks/pipeline_steps_convertor.go
  backend/plugins/circleci/models/job.go
  backend/plugins/circleci/models/workflow.go
  backend/plugins/circleci/tasks/job_extractor.go
  backend/plugins/circleci/tasks/workflow_extractor.go
  backend/plugins/dora/tasks/deployment_commits_generator.go
  backend/plugins/github/tasks/cicd_job_convertor.go
  backend/plugins/github/tasks/cicd_run_convertor.go
  backend/plugins/github/tasks/deployment_convertor.go
  backend/plugins/gitlab/e2e/snapshot_tables/cicd_deployment_commits.csv
  backend/plugins/gitlab/e2e/snapshot_tables/cicd_deployments.csv
  backend/plugins/gitlab/e2e/snapshot_tables/cicd_pipelines.csv
  backend/plugins/gitlab/e2e/snapshot_tables/cicd_tasks.csv
  backend/plugins/gitlab/e2e/snapshot_tables/cicd_tasks_no_prod_regex.csv
  backend/plugins/gitlab/tasks/deployment_convertor.go
  backend/plugins/gitlab/tasks/job_convertor.go
  backend/plugins/gitlab/tasks/pipeline_convertor.go
  backend/plugins/jenkins/e2e/snapshot_tables/cicd_pipelines.csv
  backend/plugins/jenkins/e2e/snapshot_tables/cicd_tasks.csv
  backend/plugins/jenkins/e2e/snapshot_tables/cicd_tasks_after_stages.csv
  backend/plugins/jenkins/tasks/build_cicd_convertor.go
  backend/plugins/jenkins/tasks/stage_convertor.go
  backend/plugins/webhook/api/deployments.go
Labels: pr-type/bug-fix

#6486 cherry pick #6484 fix(pipeline): fix potiential panic to v0.20
  backend/core/runner/run_pipeline.go
Labels: cherrypick

#6487 cherry pick #6484 fix(pipeline): fix potiential panic to v0.19
  backend/core/runner/run_pipeline.go
Labels: cherrypick

#6488 fix(bamboo): update tool layer table `_tool_bamboo_plan_build_commits`'s schema
  backend/plugins/bamboo/models/migrationscripts/20231121_add_missing_primary_key.go
  backend/plugins/bamboo/models/migrationscripts/register.go
Labels: needs-cherrypick-v0.19, needs-cherrypick-v0.20

#6489 cherry pick #6488 fix(bamboo): update tool layer table _tool_bamboo_plan_build_commits's schema to v0.19
  backend/plugins/bamboo/models/migrationscripts/20231121_add_missing_primary_key.go
  backend/plugins/bamboo/models/migrationscripts/register.go
Labels: cherrypick

#6476 feat(schema): add `original_status` and `original_result` fields to all related devops tables
  backend/core/models/domainlayer/devops/cicd_deployment.go
  backend/core/models/domainlayer/devops/cicd_deployment_commit.go
  backend/core/models/domainlayer/devops/cicd_pipeline.go
  backend/core/models/domainlayer/devops/cicd_task.go
  backend/core/models/migrationscripts/20231116_add_original_status_and_result_to_devops_tables.go
  backend/core/models/migrationscripts/register.go
  backend/plugins/bamboo/e2e/snapshot_tables/cicd_deployment_commits.csv
  backend/plugins/bamboo/e2e/snapshot_tables/cicd_deployments.csv
  backend/plugins/bamboo/e2e/snapshot_tables/cicd_pipelines.csv
  backend/plugins/bamboo/e2e/snapshot_tables/cicd_tasks.csv
  backend/plugins/bamboo/tasks/deploy_build_convertor.go
  backend/plugins/bamboo/tasks/job_build_convertor.go
  backend/plugins/bamboo/tasks/plan_build_convertor.go
  backend/plugins/bitbucket/e2e/deployments_test.go
  backend/plugins/bitbucket/e2e/pipeline_steps_test.go
  backend/plugins/bitbucket/e2e/pipelines_test.go
  backend/plugins/bitbucket/e2e/snapshot_tables/cicd_deployment_commits_for_deployment.csv
  backend/plugins/bitbucket/e2e/snapshot_tables/cicd_deployments_for_deployment.csv
  backend/plugins/bitbucket/e2e/snapshot_tables/cicd_pipelines.csv
  backend/plugins/bitbucket/e2e/snapshot_tables/cicd_tasks.csv
  backend/plugins/bitbucket/tasks/deployment_convertor.go
  backend/plugins/bitbucket/tasks/pipeline_convertor.go
  backend/plugins/bitbucket/tasks/pipeline_steps_convertor.go
  backend/plugins/circleci/e2e/snapshot_tables/cicd_pipelines.csv
  backend/plugins/circleci/e2e/snapshot_tables/cicd_tasks.csv
  backend/plugins/circleci/tasks/job_converter.go
  backend/plugins/circleci/tasks/workflow_converter.go
  backend/plugins/dora/tasks/deployment_commits_generator.go
  backend/plugins/github/e2e/snapshot_tables/cicd_deployment_commits.csv
  backend/plugins/github/e2e/snapshot_tables/cicd_deployments.csv
  backend/plugins/github/e2e/snapshot_tables/cicd_pipelines.csv
  backend/plugins/github/e2e/snapshot_tables/cicd_tasks.csv
  backend/plugins/github/tasks/cicd_job_convertor.go
  backend/plugins/github/tasks/cicd_run_convertor.go
  backend/plugins/github/tasks/cicd_run_extractor.go
  backend/plugins/github/tasks/deployment_convertor.go
  backend/plugins/gitlab/e2e/snapshot_tables/cicd_deployment_commits.csv
  backend/plugins/gitlab/e2e/snapshot_tables/cicd_deployments.csv
  backend/plugins/gitlab/e2e/snapshot_tables/cicd_pipelines.csv
  backend/plugins/gitlab/e2e/snapshot_tables/cicd_tasks.csv
  backend/plugins/gitlab/e2e/snapshot_tables/cicd_tasks_no_prod_regex.csv
  backend/plugins/gitlab/tasks/deployment_convertor.go
  backend/plugins/gitlab/tasks/job_convertor.go
  backend/plugins/gitlab/tasks/pipeline_convertor.go
  backend/plugins/jenkins/e2e/builds_test.go
  backend/plugins/jenkins/e2e/snapshot_tables/cicd_pipelines.csv
  backend/plugins/jenkins/e2e/snapshot_tables/cicd_tasks.csv
  backend/plugins/jenkins/e2e/snapshot_tables/cicd_tasks_after_stages.csv
  backend/plugins/jenkins/e2e/stages_test.go
  backend/plugins/jenkins/tasks/build_cicd_convertor.go
  backend/plugins/jenkins/tasks/stage_convertor.go
  backend/plugins/webhook/api/deployments.go
Labels: pr-type/feature-development

#6513 fix: panic during github_graphql task when grabbing deployments
  backend/plugins/github_graphql/tasks/deployment_collector_extractor.go
Labels: needs-cherrypick-v0.20

#6483 fix: yarn library license issues
  LICENSE
  config-ui/.yarn/releases/yarn-3.4.1.cjs
Labels: bot/auto-cherry-pick-for-release-v0.19, bot/auto-cherry-pick-for-release-v0.20

#6525 fix(config-ui): add label UTC to sync frequency
  config-ui/src/config/cron.ts
Labels: needs-cherrypick-v0.20

#6534 cherry pick #6505 fix(db): add missing primary keys to v0.20
  backend/core/models/locking.go
  backend/plugins/bitbucket/models/migrationscripts/20231123_add_primary_key_for_bitbucket_pipeline_steps.go
  backend/plugins/bitbucket/models/migrationscripts/register.go
  backend/plugins/teambition/models/migrationscripts/20231123_recreate_teambition_connections.go
  backend/plugins/teambition/models/migrationscripts/register.go
  backend/server/services/locking.go
Labels: cherrypick

#6538 feat(api): add sanitizer to remove sensitive fields
  backend/plugins/starrocks/api/connection.go
  backend/server/api/blueprints/blueprints.go
  backend/server/api/pipelines/pipelines.go
  backend/server/api/task/task.go
  backend/server/services/blueprint.go
  backend/server/services/pipeline.go
  backend/server/services/pipeline_runner.go
  backend/server/services/project.go
  backend/server/services/task.go
Labels: pr-type/feature-development

#6541 fix: incorrect datetime value: '0000-00-00' for column latest_updated…
  backend/plugins/github_graphql/tasks/deployment_collector_extractor.go
Labels: needs-cherrypick-v0.20
