Repository apache/incubator-devlake, pull requests merged in 2023-08, with the labels that each got.

#5746 [fix-5689]: Python schema migrations must be fully manual
  backend/python/README.md
  backend/python/plugins/azuredevops/azuredevops/migrations.py
  backend/python/plugins/azuredevops/azuredevops/models.py
  backend/python/pydevlake/pydevlake/__init__.py
  backend/python/pydevlake/pydevlake/message.py
  backend/python/pydevlake/pydevlake/migration.py
  backend/python/pydevlake/pydevlake/model.py
  backend/python/pydevlake/pydevlake/model_info.py
  backend/python/pydevlake/pydevlake/plugin.py
  backend/python/test/fakeplugin/fakeplugin/main.py
  backend/python/test/fakeplugin/fakeplugin/migrations.py
  backend/python/test/fakeplugin/fakeplugin/models.py
  backend/server/services/remote/init.go
  backend/server/services/remote/models/conversion.go
  backend/server/services/remote/models/migration.go
  backend/server/services/remote/models/plugin_remote.go
  backend/server/services/remote/plugin/plugin_impl.go
Labels: pr-type/bug-fix, component/pydevlake

#5785 fix: Support explicit auto-increment fields in Python
  backend/core/models/dynamic_tabler.go
  backend/python/plugins/azuredevops/azuredevops/migrations.py
  backend/python/pydevlake/pydevlake/__init__.py
  backend/python/pydevlake/pydevlake/model.py
  backend/server/services/remote/models/conversion.go
  backend/server/services/remote/models/migration.go
Labels: pr-type/bug-fix, component/pydevlake

#5793 fix(config-ui): project name transfer error
  config-ui/src/pages/project/home/index.tsx
Labels: needs-cherrypick-v0.18

#5789 fix: azuredevops reported jobs.start_time missing
  backend/impls/dalgorm/dalgorm.go
  backend/python/plugins/azuredevops/azuredevops/migrations.py
  backend/python/pydevlake/pydevlake/migration.py
  backend/server/services/remote/models/migration.go
Labels: needs-cherrypick-v0.18

#5815 fix: titles of PR time to merge panels
  grafana/dashboards/EngineeringOverview.json
Labels: needs-cherrypick-v0.18

#5811 fix: cfr validation SQL in DORA validation
  grafana/dashboards/DORADebug.json
Labels: needs-cherrypick-v0.18

#5817 cherry-pick / port fix: azuredevops reported jobs.start_time missing to v0.18 (beta4)
  backend/impls/dalgorm/dalgorm.go
  backend/python/plugins/azuredevops/azuredevops/models.py
  backend/python/pydevlake/pydevlake/migration.py
  backend/server/services/remote/models/migration.go
Labels: cherrypick

#5818 feat: add Azure DevOps dashboard
  grafana/dashboards/AzureDevOps.json
  grafana/dashboards/Homepage.json
Labels: needs-cherrypick-v0.18

#5870 Cherry pick#5869 to release-v0.18
  backend/plugins/zentao/api/proxy.go
  backend/plugins/zentao/impl/impl.go
Labels: cherrypick

#5881 fix: zentao issue url
  backend/plugins/zentao/e2e/snapshot_tables/issues_bug.csv
  backend/plugins/zentao/e2e/snapshot_tables/issues_story.csv
  backend/plugins/zentao/e2e/snapshot_tables/issues_task.csv
  backend/plugins/zentao/tasks/bug_convertor.go
  backend/plugins/zentao/tasks/shared.go
  backend/plugins/zentao/tasks/shared_test.go
  backend/plugins/zentao/tasks/story_convertor.go
  backend/plugins/zentao/tasks/task_convertor.go
Labels: needs-cherrypick-v0.18

#5890 fix: A MTTR case summary can not show
  grafana/dashboards/DORA.json
  grafana/dashboards/DORAByTeam.json
  grafana/dashboards/DORADebug.json
Labels: needs-cherrypick-v0.18

#5900 fix: github account collection might fail with 404
  backend/plugins/github_graphql/tasks/account_graphql_pre_extractor.go
  backend/plugins/github_graphql/tasks/issue_collector.go
  backend/plugins/github_graphql/tasks/pr_collector.go
Labels: needs-cherrypick-v0.18

#5905 fix: zentao plugin parsing JSON error
  backend/plugins/zentao/models/bug_commits.go
  backend/plugins/zentao/models/story_commits.go
  backend/plugins/zentao/models/task_commits.go
Labels: needs-cherrypick-v0.18

#5908 fix: converting pipelines to deployments should ignore skipped items
  backend/core/models/domainlayer/devops/cicd_pipeline.go
  backend/plugins/bamboo/tasks/deploy_build_convertor.go
  backend/plugins/bamboo/tasks/job_build_convertor.go
  backend/plugins/bamboo/tasks/plan_build_convertor.go
  backend/plugins/bitbucket/tasks/deployment_convertor.go
  backend/plugins/bitbucket/tasks/pipeline_convertor.go
  backend/plugins/bitbucket/tasks/pipeline_steps_convertor.go
  backend/plugins/dora/e2e/deployment_generator/cicd_deployment_commits.csv
  backend/plugins/dora/e2e/deployment_generator/cicd_pipeline_commits.csv
  backend/plugins/dora/e2e/deployment_generator/cicd_pipelines.csv
  backend/plugins/dora/e2e/deployment_generator/cicd_tasks.csv
  backend/plugins/dora/tasks/deployment_commits_generator.go
  backend/plugins/dora/tasks/incident_deploy_connector.go
  backend/plugins/dora/tasks/prev_deployment_commit_enricher.go
  backend/plugins/github/tasks/cicd_job_convertor.go
  backend/plugins/github/tasks/cicd_run_convertor.go
  backend/plugins/gitlab/tasks/job_convertor.go
  backend/plugins/gitlab/tasks/pipeline_convertor.go
  backend/plugins/jenkins/e2e/builds_test.go
  backend/plugins/jenkins/impl/impl.go
  backend/plugins/jenkins/tasks/build_cicd_convertor.go
  backend/plugins/jenkins/tasks/stage_convertor.go
  backend/plugins/webhook/api/deployments.go
Labels: needs-cherrypick-v0.18

#5910 fix: rerun failed with LOCK TABLE
  backend/server/services/pipeline.go
Labels: needs-cherrypick-v0.18

#5931 cherry-pick fix(zentao): get all bugs(include closed bugs) to v0.18 (beta7)
  backend/plugins/zentao/tasks/bug_collector.go
Labels: cherrypick

#5943 cherry-pick type mapping and time calculation fixes to v0.18(beta7)
  backend/plugins/zentao/e2e/snapshot_tables/issues_task.csv
  backend/plugins/zentao/e2e/task_test.go
  backend/plugins/zentao/tasks/bug_collector.go
  backend/plugins/zentao/tasks/task_convertor.go
  backend/server/services/blueprint.go
Labels: cherrypick

#5944 cherry-pick fix(zentao): remove execution's product stories to v0.18(beta7)
  backend/helpers/pluginhelper/api/api_collector.go
  backend/helpers/pluginhelper/api/data_convertor.go
  backend/plugins/zentao/tasks/department_convertor.go
  backend/plugins/zentao/tasks/iterator.go
  backend/plugins/zentao/tasks/project_convertor.go
  backend/plugins/zentao/tasks/story_collector.go
Labels: cherrypick

#5946 GitHub fails after upgrade to v0.18
  backend/core/plugin/plugin_blueprint.go
  backend/plugins/github/models/migrationscripts/20230612_add_fullName.go
Labels: needs-cherrypick-v0.18

#5950 fix: Whitelist external source providers types
  backend/python/plugins/azuredevops/azuredevops/main.py
Labels: needs-cherrypick-v0.18

#5951 fix: skip invalid account in case there were corrupted records in the database
  backend/plugins/github/tasks/account_org_collector.go
Labels: needs-cherrypick-v0.18

#5952 cherry-pick #5951 fix: skip invalid account in case there were corruptted records in the db to v0.18 (beta8)
  backend/plugins/github/tasks/account_org_collector.go
Labels: cherrypick

#5953 cherry-pick fix: Whitelist external source providers types #5950 to v0.18 (beta 8)
  backend/python/plugins/azuredevops/azuredevops/main.py
Labels: cherrypick

#5959 cherry-pick fix jenkins remote scopes API, add GetRemoteScopesOutput for remoteHelper to v0.18(beta8)
  .github/workflows/commit-msg.yml
  backend/helpers/pluginhelper/api/remote_api_helper.go
  backend/plugins/bamboo/api/remote.go
  backend/plugins/bitbucket/api/remote.go
  backend/plugins/github/api/remote.go
  backend/plugins/gitlab/api/remote.go
  backend/plugins/jenkins/api/jobs.go
  backend/plugins/jenkins/api/remote.go
  backend/plugins/jira/api/remote.go
  backend/plugins/sonarqube/api/remote.go
  backend/plugins/tapd/api/remote.go
  backend/plugins/zentao/api/remote.go
Labels: cherrypick

#5963 cherry-pic fix(zentao): update zentao plugin, do lots of fixes
  backend/plugins/zentao/e2e/snapshot_tables/issues_story.csv
  backend/plugins/zentao/tasks/bug_collector.go
  backend/plugins/zentao/tasks/bug_repo_commits_extractor.go
  backend/plugins/zentao/tasks/project_convertor.go
  backend/plugins/zentao/tasks/shared.go
  backend/plugins/zentao/tasks/shared_test.go
  backend/plugins/zentao/tasks/story_convertor.go
  backend/plugins/zentao/tasks/story_repo_commits_extractor.go
  backend/plugins/zentao/tasks/task_repo_commits_extractor.go
Labels: cherrypick

#5971 cherry-pick fix(zentao): fix completed_date and ended_date fields
  backend/plugins/zentao/e2e/snapshot_tables/execution_sprint.csv
  backend/plugins/zentao/tasks/execution_convertor.go
Labels: cherrypick

#5973 fix(zentao): get all exeutions(include closed) under a project
  backend/plugins/zentao/tasks/execution_summary_collector.go
Labels: cherrypick-completed

#5975 cherry-pick fix(zentao): get all exeutions(include closed) under a project #5973
  backend/plugins/zentao/tasks/execution_summary_collector.go
Labels: cherrypick

#5981 cherry-pick update sprint's url field
  backend/core/runner/basic_res.go
  backend/go.mod
  backend/go.sum
  backend/plugins/zentao/e2e/account_test.go
  backend/plugins/zentao/e2e/bug_commits_test.go
  backend/plugins/zentao/e2e/bug_test.go
  backend/plugins/zentao/e2e/changelog_test.go
  backend/plugins/zentao/e2e/execution_test.go
  backend/plugins/zentao/e2e/snapshot_tables/execution_sprint.csv
  backend/plugins/zentao/e2e/story_commits_test.go
  backend/plugins/zentao/e2e/story_test.go
  backend/plugins/zentao/e2e/task_commits_test.go
  backend/plugins/zentao/e2e/task_test.go
  backend/plugins/zentao/tasks/execution_convertor.go
  backend/plugins/zentao/tasks/project_convertor.go
  backend/plugins/zentao/tasks/shared.go
  backend/plugins/zentao/tasks/shared_test.go
Labels: cherrypick

#5987 fix(config-ui): error project name convert
  config-ui/src/pages/blueprint/connection-detail/index.tsx
  config-ui/src/pages/blueprint/detail/configuration-panel.tsx
Labels: needs-cherrypick-v0.18
