Repository apache/incubator-devlake, pull requests merged in 2023-07, with the labels that each got.

#5604 [refactor-5602]: Remove support for Zentao products
  backend/core/utils/table_info_checker.go
  backend/helpers/e2ehelper/data_flow_tester.go
  backend/plugins/zentao/api/init.go
  backend/plugins/zentao/api/project_scope.go
  backend/plugins/zentao/api/remote.go
  backend/plugins/zentao/api/scope.go
  backend/plugins/zentao/impl/impl.go
  backend/scripts/compile-plugins.sh
Labels: type/refactor

#5623 fix: SQL typo in engineering overview dashboard
  grafana/dashboards/EngineeringOverview.json
Labels: needs-cherrypick-v0.17

#5671 fix: image license
  LICENSE
  config-ui/src/images/icons/dashborad.svg
Labels: needs-cherrypick-v0.17

#5685 fix: sonarqube lastAnalysisDate string to iso8601Time
  backend/plugins/sonarqube/api/scope.go
Labels: needs-cherrypick-v0.18

#5701 fix: azuredevops automigrate failed on newer gorm
  backend/server/services/remote/models/models.go
  backend/server/services/remote/plugin/plugin_impl.go
Labels: needs-cherrypick-v0.18

#5702 fix: no pipelines data when running pipelines on postgres
  backend/helpers/dbhelper/txhelper.go
  backend/server/services/pipeline.go
Labels: needs-cherrypick-v0.18

#5708 fix: azuredevops returning illegal response
  backend/server/services/remote/plugin/scope_api.go
Labels: needs-cherrypick-v0.18

#5709 cherry-pick #5708 azuredevops scope APIs returning illegal response to v0.18 (beta2)
  backend/server/services/remote/plugin/scope_api.go
Labels: cherrypick

#5711 fix: pipeline dequeue deadlock
  backend/server/services/pipeline.go
Labels: needs-cherrypick-v0.18

#5710 fix: skipCollectors add default value
  backend/server/api/blueprints/blueprints.go
Labels: needs-cherrypick-v0.18

#5713 cherry-pick #5711 fix: pipeline dequeue deadlock to v0.18 (beta2)
  backend/server/services/pipeline.go
Labels: cherrypick

#5717 fix: starrocks panic with new tables
  backend/impls/dalgorm/dalgorm.go
Labels: needs-cherrypick-v0.18

#5722 fix: GetScopes panic on Advanced BP
  backend/helpers/pluginhelper/services/blueprint_helper.go
  config-ui/src/pages/blueprint/home/index.tsx
Labels: needs-cherrypick-v0.18

#5714 [fix-5697][Pydevlake]: Fix AddColumn op possibly deleting a column
  backend/python/plugins/azuredevops/azuredevops/models.py
  backend/server/services/remote/models/migration.go
  backend/server/services/remote/plugin/plugin_impl.go
Labels: pr-type/bug-fix, needs-cherrypick-v0.18

#5726 fix: unify scopeConfig field for task_data
  backend/plugins/bitbucket/tasks/task_data.go
  backend/plugins/tapd/tasks/task_data.go
  backend/plugins/zentao/tasks/task_data.go
Labels: needs-cherrypick-v0.18

#5728 cherry-pick #5726 fix: unify scopeConfig field for task_data to v0.18 (beta3)
  backend/plugins/bitbucket/tasks/task_data.go
  backend/plugins/tapd/tasks/task_data.go
  backend/plugins/zentao/tasks/task_data.go
Labels: cherrypick

#5731 cherrypick(v0.18.0-beta3): #5697
  backend/python/plugins/azuredevops/azuredevops/models.py
  backend/server/services/remote/models/migration.go
  backend/server/services/remote/plugin/plugin_impl.go
Labels: needs-cherrypick-v0.18

#5674 [doc-4391]: Rework developer's manual docs
  README.md
  backend/DevelopmentManual.md
  backend/generator/README.md
  backend/generator/cmd/create_collector.go
  backend/generator/cmd/create_extractor.go
  backend/generator/cmd/create_migration.go
  backend/generator/cmd/create_plugin.go
  backend/generator/cmd/e2e_raw_create.go
  backend/generator/cmd/generator_doc.go
  backend/generator/cmd/init_migration.go
  backend/generator/cmd/root.go
  backend/generator/docs/generator.md
  backend/generator/docs/generator_completion.md
  backend/generator/docs/generator_completion_bash.md
  backend/generator/docs/generator_completion_fish.md
  backend/generator/docs/generator_completion_powershell.md
  backend/generator/docs/generator_completion_zsh.md
  backend/generator/docs/generator_create-collector.md
  backend/generator/docs/generator_create-e2e-raw.md
  backend/generator/docs/generator_create-extractor.md
  backend/generator/docs/generator_create-migration.md
  backend/generator/docs/generator_create-plugin.md
  backend/generator/docs/generator_generator-doc.md
  backend/generator/docs/generator_init-migration.md
  backend/generator/main.go
  backend/generator/template/migrationscripts/add_init_tables.go-template
  backend/generator/template/migrationscripts/archived/connection.go-template
  backend/generator/template/migrationscripts/migration.go-template
  backend/generator/template/migrationscripts/migration_with_config.go-template
  backend/generator/template/migrationscripts/register.go-template
  backend/generator/template/plugin/api/blueprint.go-template
  backend/generator/template/plugin/api/connection.go-template
  backend/generator/template/plugin/api/init.go-template
  backend/generator/template/plugin/impl/impl_complete_plugin.go-template
  backend/generator/template/plugin/models/connection.go-template
  backend/generator/template/plugin/plugin_main.go-template
  backend/generator/template/plugin/plugin_main_complete_plugin.go-template
  backend/generator/template/plugin/tasks/api_client.go-template
  backend/generator/template/plugin/tasks/api_collector.go-template
  backend/generator/template/plugin/tasks/extractor.go-template
  backend/generator/template/plugin/tasks/shared.go-template
  backend/generator/template/plugin/tasks/task_data.go-template
  backend/generator/template/plugin/tasks/task_data_complete_plugin.go-template
  backend/generator/util/template.go
  backend/python/README.md
Labels: type/docs, component/docs

#5736 fix: apicollector might report table exists when running in parallel
  backend/helpers/pluginhelper/api/api_collector.go
Labels: needs-cherrypick-v0.18

#5724 feat: add full name to remote api
  backend/Makefile
  backend/core/plugin/plugin_scope_abstract.go
  backend/helpers/pluginhelper/api/remote_api_helper.go
  backend/helpers/pluginhelper/api/scope_helper_test.go
  backend/plugins/bamboo/models/project.go
  backend/plugins/bitbucket/models/repo.go
  backend/plugins/gitee/models/repo.go
  backend/plugins/github/models/repo.go
  backend/plugins/gitlab/models/project.go
  backend/plugins/jenkins/models/job.go
  backend/plugins/jira/models/board.go
  backend/plugins/pagerduty/models/service.go
  backend/plugins/sonarqube/models/sonarqube_project.go
  backend/plugins/tapd/models/workspace.go
  backend/plugins/trello/models/board.go
  backend/plugins/zentao/models/project.go
  backend/server/services/remote/models/models.go
Labels: needs-cherrypick-v0.18

#5757 fix: zentao status/type mapping
  backend/plugins/zentao/tasks/bug_convertor.go
  backend/plugins/zentao/tasks/bug_extractor.go
  backend/plugins/zentao/tasks/story_convertor.go
  backend/plugins/zentao/tasks/story_extractor.go
  backend/plugins/zentao/tasks/task_convertor.go
Labels: needs-cherrypick-v0.18

#5754 fix(config-ui): missed full name when search scope selected
  config-ui/src/plugins/components/data-scope-select-remote/index.tsx
Labels: needs-cherrypick-v0.18

#5776 feat: add PagerDuty dashboard
  grafana/dashboards/Homepage.json
  grafana/dashboards/PagerDuty.json
Labels: pr-type/feature-development, component/ext
