Repository apache/incubator-devlake, pull requests merged in 2023-03, with the labels that each got.

#4551 fix: add some log; wait when query fail in RunPipelineInQueue
  backend/core/models/blueprint.go
  backend/plugins/webhook/api/blueprint_v200.go
  backend/server/services/pipeline.go
Labels: pr-type/bug-fix

#4598 fix: check nil for HeadRef and BaseRef
  backend/plugins/bitbucket/tasks/pr_extractor.go
Labels: pr-type/bug-fix

#4668 fix: decrease page size for github graphql pr collector
  backend/plugins/github_graphql/tasks/pr_collector.go
Labels: pr-type/bug-fix

#4778 test: Support for remote debugging of Python src code
  backend/python/README.md
  backend/python/plugins/azuredevops/README.md
  backend/python/pydevlake/README.md
  backend/python/pydevlake/pydevlake/helpers/debugger.py
  backend/python/pydevlake/pydevlake/ipc.py
  backend/python/pydevlake/pydevlake/plugin.py
  backend/test/integration/helper/client.go
  backend/test/integration/remote/helper.go
  backend/test/integration/remote/python_plugin_test.go
Labels: component/testing

#4813 [v0.16.0-beta11] Dockerfile fixes from issues #4734 and #4781
  backend/Dockerfile
Labels: devops, cherrypick

#4818 fix(Pagerduty): Ticket scopes fix in Blueprint creation
  backend/plugins/pagerduty/api/blueprint_v200.go
  backend/plugins/pagerduty/api/transformation_rules.go
  backend/plugins/pagerduty/impl/impl.go
Labels: component/plugins

#4815 [fix-4772]: Python progress update crashes Go DevLake server
  backend/core/utils/ipc.go
  backend/go.mod
  backend/python/pydevlake/pydevlake/__init__.py
  backend/python/pydevlake/pydevlake/helpers/debugger.py
  backend/python/pydevlake/pydevlake/ipc.py
  backend/python/pydevlake/pydevlake/subtasks.py
  backend/python/test/fakeplugin/fakeplugin/main.py
  backend/server/services/remote/bridge/bridge.go
Labels: component/framework, component/testing

#4837 test: Have Python changes trigger GitHub actions
  .github/workflows/test-e2e.yml
  .github/workflows/test.yml
Labels: devops, component/testing
