Repository apache/incubator-devlake, pull requests merged in 2023-10, with the labels that each got.

#6176 [refactor-5939]: Remove Temporal support
  Makefile
  backend/Makefile
  backend/core/config/config_viper.go
  backend/go.mod
  backend/server/services/pipeline.go
  backend/server/services/pipeline_runner.go
  backend/server/services/task.go
  backend/server/services/task_runner.go
  backend/worker/app/logger.go
  backend/worker/app/pipeline_workflow.go
  backend/worker/app/shared.go
  backend/worker/app/task_activity.go
  backend/worker/main.go
Labels: type/refactor

#6196 fix: data too long for column file_metrics_key in postgres
  backend/plugins/sonarqube/models/migrationscripts/20230927_modify_file_metrics_key_length.go
Labels: needs-cherrypick-v0.19

#6226 fix(config-ui): adjust the config for nginx
  config-ui/nginx.conf
Labels: needs-cherrypick-v0.19

#6270 fix: pr should be connected to failed deployment commit
  backend/plugins/dora/e2e/calculate_change_lead_time_test.go
  backend/plugins/dora/e2e/change_lead_time/commits_diffs.csv
  backend/plugins/dora/e2e/change_lead_time/project_mapping.csv
  backend/plugins/dora/e2e/change_lead_time/project_pr_metrics.csv
  backend/plugins/dora/e2e/change_lead_time/pull_requests.csv
  backend/plugins/dora/tasks/change_lead_time_calculator.go
Labels: needs-cherrypick-v0.18, needs-cherrypick-v0.19

#6315 fix: update sonarqube issue collector by type/status/severity
  backend/plugins/sonarqube/tasks/issues_collector.go
Labels: needs-cherrypick-v0.19

#6331 fix: ReloadBlueprints is not safe
  backend/helpers/dbhelper/txhelper.go
  backend/server/services/blueprint.go
Labels: needs-cherrypick-v0.19

#6342 fix: tapd story changelog connecting to record from another connection
  backend/helpers/e2ehelper/data_flow_tester.go
  backend/plugins/tapd/e2e/story_changelog_test.go
  backend/plugins/tapd/tasks/story_changelog_converter.go
Labels: needs-cherrypick-v0.19

#6350 fix: missing connectionId from tapd labels
  backend/plugins/tapd/models/bug_label.go
  backend/plugins/tapd/models/migrationscripts/20231026_add_connection_id_to_labels.go
  backend/plugins/tapd/models/migrationscripts/register.go
  backend/plugins/tapd/models/story_label.go
  backend/plugins/tapd/models/task_label.go
  backend/plugins/tapd/tasks/bug_changelog_converter.go
  backend/plugins/tapd/tasks/bug_label_convertor.go
  backend/plugins/tapd/tasks/story_label_convertor.go
  backend/plugins/tapd/tasks/task_changelog_converter.go
  backend/plugins/tapd/tasks/task_label_convertor.go
Labels: needs-cherrypick-v0.19
