Repository apache/incubator-devlake, pull requests merged in 2024-02, with the labels that each got.

#6901 fix: triggering blueprint concurrently might lead to deadlock
  backend/server/services/pipeline.go
  backend/server/services/pipeline_helper.go
  backend/server/services/task.go
Labels: needs-cherrypick-v0.20, needs-cherrypick-v0.21

#6902 cherry-pick #6901 fix: triggering blueprint concurrently might lead to deadlock
  backend/server/services/pipeline.go
  backend/server/services/pipeline_helper.go
  backend/server/services/task.go
Labels: needs-cherrypick-v0.21

#6912 [fix-6824]: AzureDevops now allows email-less commits
  backend/python/plugins/azuredevops/azuredevops/models.py
Labels: pr-type/bug-fix

#6911 [fix-6818]: AzDo connection names are now unique
  backend/python/pydevlake/pydevlake/model.py
  backend/server/services/remote/models/migrationscripts/azuredevops/azuredevops_20240201_unique_connection_name.go
  backend/server/services/remote/models/migrationscripts/register.go
Labels: pr-type/bug-fix

#6913 fix: adjust the margin for page layout
  config-ui/src/components/page-header/styled.ts
  config-ui/src/routes/api-keys/api-keys.tsx
Labels: needs-cherrypick-v0.21

#6922 chore: upgrade antd to 5.14.0
  config-ui/package.json
  config-ui/src/routes/blueprint/detail/components/sync-policy/index.tsx
  config-ui/yarn.lock
Labels: needs-cherrypick-v0.21

#6925 fix: default value error in jira transformation
  config-ui/src/plugins/register/jira/config.tsx
Labels: needs-cherrypick-v0.21

#6928 fix: missed redirect path prefix in connection detail
  config-ui/src/routes/blueprint/connection-detail/index.tsx
Labels: needs-cherrypick-v0.21

#6932 fix: rerun task deadlock
  backend/server/services/pipeline.go
Labels: needs-cherrypick-v0.21

#6935 fix: new dshelper does not set raw data origin properly
  backend/helpers/pluginhelper/api/ds_scope_api_helper.go
  backend/helpers/pluginhelper/api/model_api_helper.go
  backend/helpers/srvhelper/scope_service_helper.go
  backend/plugins/bamboo/models/migrationscripts/20230630_add_raw_param_table_for_scopes.go
  backend/plugins/bitbucket/models/migrationscripts/20230630_add_raw_param_table_for_scopes.go
  backend/plugins/github/models/migrationscripts/20230630_add_raw_param_table_for_scopes.go
  backend/plugins/gitlab/models/migrationscripts/20230630_add_raw_param_table_for_scopes.go
  backend/plugins/jira/models/migrationscripts/20230630_add_raw_param_table_for_scopes.go
  backend/plugins/sonarqube/models/migrationscripts/20230630_add_raw_param_table_for_scopes.go
Labels: needs-cherrypick-v0.21

#6937 feat: add default name for scope config
  config-ui/src/plugins/components/scope-config-form/index.tsx
  config-ui/src/plugins/components/scope-config-select/index.tsx
Labels: needs-cherrypick-v0.21

#6939 fix: rerun pipeline deadlock
  backend/server/api/task/task.go
  backend/server/services/pipeline.go
  backend/server/services/task.go
Labels: needs-cherrypick-v0.21

#6931 fix: deployment dora dashboard
  backend/plugins/dora/models/migrationscripts/20240207_add_dora_2023_benchmark.go
  grafana/dashboards/DORA.json
  grafana/dashboards/DORAByTeam.json
  grafana/dashboards/DORADebug.json
Labels: needs-cherrypick-v0.21

#6955 chore: adds support for IPv6 in nginx
  config-ui/nginx.conf
Labels: needs-cherrypick-v0.21

#6966 fix: /grafana should be off
  config-ui/nginx.conf
Labels: needs-cherrypick-v0.21

#6969 fix(backend): update log message when reading configurations
  backend/core/config/config_viper.go
Labels: pr-type/bug-fix

#6986 fix(zentao): update the type of `PriOrder`
  backend/plugins/zentao/models/story.go
  backend/plugins/zentao/models/task.go
  backend/plugins/zentao/tasks/story_extractor.go
  backend/plugins/zentao/tasks/task_extractor.go
Labels: pr-type/bug-fix

#6995 refactor: optimize bp cronjob scheduling
  backend/server/services/blueprint.go
  backend/server/services/pipeline.go
Labels: needs-cherrypick-v0.21

#7001 fix(azuredevops): fix some fields' value
  backend/core/models/domainlayer/code/repo.go
  backend/core/plugin/hub.go
  backend/python/plugins/azuredevops/azuredevops/main.py
  backend/python/plugins/azuredevops/azuredevops/migrations.py
  backend/python/plugins/azuredevops/azuredevops/models.py
  backend/python/plugins/azuredevops/azuredevops/streams/pull_requests.py
  backend/python/plugins/azuredevops/tests/streams_test.py
  backend/python/pydevlake/pydevlake/plugin.py
Labels: needs-cherrypick-v0.21

#7013 [AzureDevops ] fix: some fields' values
  backend/python/plugins/azuredevops/azuredevops/main.py
  backend/python/plugins/azuredevops/azuredevops/streams/builds.py
  backend/python/plugins/azuredevops/azuredevops/streams/jobs.py
  backend/python/plugins/azuredevops/azuredevops/streams/pull_requests.py
  backend/python/pydevlake/pydevlake/domain_layer/devops.py
Labels: needs-cherrypick-v0.21, bot/auto-cherry-pick-for-release-v0.21

#7016 [jira test connection api]fix: invalid url detection not working correctly
  backend/plugins/jira/api/connection_api.go
Labels: needs-cherrypick-v0.21

#7018 fix(gitextractor): cover errors that may leak sensitive information
  backend/plugins/gitextractor/parser/clone.go
Labels: needs-cherrypick-v0.21, bot/auto-cherry-pick-for-release-v0.21

#7022 fix(azuredevops): fix unexpected environment field in cicd_tasks and …
  backend/python/pydevlake/pydevlake/domain_layer/devops.py
Labels: needs-cherrypick-v0.21, bot/auto-cherry-pick-for-release-v0.21

#7011 feat: missed circleci transformation
  config-ui/src/plugins/components/scope-config-form/index.tsx
  config-ui/src/plugins/components/scope-config-form/misc.ts
  config-ui/src/plugins/register/circleci/index.ts
  config-ui/src/plugins/register/circleci/transformation.tsx
  config-ui/src/release/stable.ts
Labels: needs-cherrypick-v0.21

#7031 fix: jira test connection error message for wrong user/pass not working
  backend/helpers/pluginhelper/api/api_client.go
  backend/plugins/github/api/remote_api.go
  backend/plugins/jira/api/connection_api.go
Labels: bot/auto-cherry-pick-for-release-v0.21

#7036 fix(dockerfile): try to fix build errors
  backend/Dockerfile
Labels: needs-cherrypick-v0.21, bot/auto-cherry-pick-for-release-v0.21

#7032 fix `updated_at` field in cicd_tasks and cicd_pipelines
  backend/python/plugins/azuredevops/azuredevops/streams/builds.py
  backend/python/plugins/azuredevops/azuredevops/streams/jobs.py
  backend/python/plugins/azuredevops/azuredevops/streams/pull_request_commits.py
  backend/python/plugins/azuredevops/azuredevops/streams/pull_requests.py
  backend/python/pydevlake/pydevlake/model.py
  backend/python/pydevlake/pydevlake/stream.py
  backend/python/pydevlake/pydevlake/subtasks.py
  backend/python/pydevlake/pydevlake/testing/testing.py
Labels: needs-cherrypick-v0.21, bot/auto-cherry-pick-for-release-v0.21

#7042 fix(tapd): sanitize connection's resp
  backend/plugins/tapd/api/connection.go
Labels: needs-cherrypick-v0.21, bot/auto-cherry-pick-for-release-v0.21

#7051 fix(zentao): fix parsing errors for date related fields on zentao v18.10
  backend/core/models/common/iso8601time.go
  backend/core/models/migrationscripts/archived/iso8601time.go
Labels: needs-cherrypick-v0.20, bot/auto-cherry-pick-for-release-v0.20

#7030 feat: add docs about v0.21
  config-ui/src/release/v0.21.ts
Labels: needs-cherrypick-v0.21

#7060 fix(azuredevops): fix environment field in cicd_tasks and cicd_pipelines
  backend/impls/logruslog/init.go
  backend/python/plugins/azuredevops/azuredevops/streams/builds.py
  backend/python/plugins/azuredevops/azuredevops/streams/jobs.py
  backend/python/pydevlake/pydevlake/domain_layer/devops.py
Labels: needs-cherrypick-v0.21, bot/auto-cherry-pick-for-release-v0.21

#7062 fix(azuredevops): remove unneccessary collectors when re-transformati…
  backend/python/pydevlake/pydevlake/plugin.py
Labels: needs-cherrypick-v0.21, bot/auto-cherry-pick-for-release-v0.21

#7064 fix(azuredevops): fix environment field
  backend/python/plugins/azuredevops/azuredevops/streams/builds.py
  backend/python/plugins/azuredevops/azuredevops/streams/jobs.py
Labels: bot/auto-cherry-pick-completed, needs-cherrypick-v0.21, bot/auto-cherry-pick-for-release-v0.21

#7066 fix: jenkins task name error
  config-ui/src/routes/pipeline/components/task.tsx
Labels: needs-cherrypick-v0.19, needs-cherrypick-v0.20, needs-cherrypick-v0.21

#7070 fix: empty dora data when run the tasks
  backend/plugins/dora/tasks/change_lead_time_calculator.go
  backend/plugins/dora/tasks/deployment_commits_generator.go
  backend/plugins/dora/tasks/deployment_generator.go
  backend/plugins/dora/tasks/incident_deploy_connector.go
Labels: needs-cherrypick-v0.21
