Repository apache/incubator-devlake, pull requests merged in 2024-01, with the labels that each got.

#6732 fix: gitlab type is nil
  backend/plugins/gitlab/e2e/snapshot_tables/_tool_gitlab_issues.csv
  backend/plugins/gitlab/tasks/issue_extractor.go
Labels: needs-cherrypick-v0.20

#6747 fix(dashboard): fix circle ci
  grafana/dashboards/CircleCI.json
Labels: pr-type/bug-fix

#6772 fix(github): fix resp when testing an existed connection
  backend/plugins/github/api/connection_api.go
Labels: pr-type/bug-fix

#6776 fix: zentao collect bug with priOrder
  backend/plugins/zentao/models/bug.go
  backend/plugins/zentao/tasks/bug_extractor.go
Labels: needs-cherrypick-v0.20

#6803 fix(sonarqube): init dsHelper
  backend/plugins/sonarqube/api/init.go
Labels: pr-type/bug-fix

#6827 fix: github original type no value
  backend/plugins/github/e2e/snapshot_tables/_tool_github_issues.csv
  backend/plugins/github/tasks/issue_extractor.go
  backend/plugins/github_graphql/tasks/issue_extractor.go
  backend/plugins/gitlab/e2e/snapshot_tables/_tool_gitlab_issues.csv
  backend/plugins/gitlab/tasks/issue_extractor.go
Labels: needs-cherrypick-v0.20

#6836 fix: circleci dashboard has same uid to the jenkins
  grafana/dashboards/CircleCI.json
Labels: needs-cherrypick-v0.20

#6793 fix: security hotfix
  config-ui/Dockerfile
  grafana/Dockerfile
Labels: needs-cherrypick-v0.18, needs-cherrypick-v0.19, needs-cherrypick-v0.20

#6841 fix: the value of incidents priority is P2, but shown in 'HIGH'
  backend/core/models/domainlayer/ticket/issue.go
  backend/core/models/migrationscripts/20240117_add_urgency_to_issues.go
  backend/core/models/migrationscripts/register.go
  backend/plugins/pagerduty/e2e/snapshot_tables/_tool_pagerduty_incidents.csv
  backend/plugins/pagerduty/e2e/snapshot_tables/issues.csv
  backend/plugins/pagerduty/tasks/incidents_converter.go
Labels: needs-cherrypick-v0.20

#6847 fix: be plugin unload error
  config-ui/src/api/plugin/index.ts
  config-ui/src/routes/layout/loader.ts
Labels: needs-cherrypick-v0.20

#6845 fix: gitlab type and severity
  backend/plugins/gitlab/e2e/snapshot_tables/_tool_gitlab_issues.csv
  backend/plugins/gitlab/e2e/snapshot_tables/issues.csv
  backend/plugins/gitlab/tasks/issue_extractor.go
Labels: needs-cherrypick-v0.20

#6850 fix: azure,bamboo,github,jira distinct primary key
  grafana/dashboards/AzureDevOps.json
  grafana/dashboards/Bamboo.json
  grafana/dashboards/GitHub.json
  grafana/dashboards/Jira.json
Labels: needs-cherrypick-v0.20

#6856 fix: remove duplicates complex dashboard sql
  grafana/dashboards/ComponentAndFileLevelMetrics.json
  grafana/dashboards/ContributorExperience.json
  grafana/dashboards/EngineeringOverview.json
  grafana/dashboards/EngineeringThroughputAndCycleTime.json
  grafana/dashboards/EngineeringThroughputAndCycleTimeTeamView.json
  grafana/dashboards/Gitlab.json
  grafana/dashboards/WeeklyBugRetro.json
  grafana/dashboards/WeeklyCommunityRetro.json
Labels: needs-cherrypick-v0.20

#6858 fix: add .md file afs header checker
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/pull_request_template.md
  .licenserc.yaml
  README.md
  backend/DevelopmentManual.md
  backend/core/models/domainlayer/README.md
  backend/plugins/circleci/README.md
  backend/plugins/customize/README.md
  backend/plugins/dbt/README.md
  backend/plugins/feishu/README.md
  backend/plugins/gitee/README.md
  backend/plugins/gitextractor/README.md
  backend/plugins/github/README.md
  backend/plugins/gitlab/README.md
  backend/plugins/jenkins/README.md
  backend/plugins/jira/README.md
  backend/plugins/refdiff/README.md
  backend/plugins/slack/README.md
  backend/plugins/trello/README.md
  backend/python/DevelopmentSetup.md
  backend/python/README.md
  backend/python/plugins/azuredevops/README.md
  backend/python/pydevlake/README.md
  backend/server/api/README.md
  backend/server/api/push/README.md
  backend/test/Readme.md
  backend/test/e2e/manual/Readme.md
  config-ui/.yarnrc.yml
  config-ui/README.md
  devops/docker/alpine-dbt/README.md
  devops/docker/lake-builder/README.md
Labels: needs-cherrypick-v0.20

#6864 fix: remove zentao department_convertor
  backend/plugins/zentao/impl/impl.go
  backend/plugins/zentao/tasks/department_convertor.go
Labels: needs-cherrypick-v0.20

#6866 fix: issue story points dashboard
  grafana/dashboards/EngineeringThroughputAndCycleTime.json
Labels: needs-cherrypick-v0.20

#6873 fix: github deployment status active and inactive should be treated as success
  backend/plugins/github/e2e/snapshot_tables/cicd_deployment_commits.csv
  backend/plugins/github/e2e/snapshot_tables/cicd_deployments.csv
  backend/plugins/github/tasks/deployment_convertor.go
Labels: needs-cherrypick-v0.20

#6882 fix: some bugs
  config-ui/src/routes/layout/layout.tsx
  config-ui/src/utils/operator.ts
Labels: needs-cherrypick-v0.21

#6886 fix: adjust the style for page header
  config-ui/src/components/page-header/index.tsx
  config-ui/src/components/page-header/styled.ts
  config-ui/src/routes/blueprint/home/index.tsx
Labels: needs-cherrypick-v0.21

#6881 fix(dashboard): update dashboards, remove warnings
  grafana/dashboards/AzureDevOps.json
  grafana/dashboards/Bamboo.json
  grafana/dashboards/BitBucket.json
  grafana/dashboards/ComponentAndFileLevelMetrics.json
  grafana/dashboards/ContributorExperience.json
  grafana/dashboards/DORA.json
  grafana/dashboards/DORAByTeam.json
  grafana/dashboards/EngineeringOverview.json
  grafana/dashboards/EngineeringThroughputAndCycleTime.json
  grafana/dashboards/EngineeringThroughputAndCycleTimeTeamView.json
  grafana/dashboards/GitHub.json
  grafana/dashboards/GithubReleaseQualityAndContributionAnalysis.json
  grafana/dashboards/Gitlab.json
  grafana/dashboards/Jenkins.json
  grafana/dashboards/Jira.json
  grafana/dashboards/Opsgenie.json
  grafana/dashboards/PagerDuty.json
  grafana/dashboards/Sonarqube.json
  grafana/dashboards/TAPD.json
  grafana/dashboards/Teambition.json
  grafana/dashboards/WeeklyBugRetro.json
  grafana/dashboards/WeeklyCommunityRetro.json
  grafana/dashboards/Zentao.json
Labels: pr-type/bug-fix

#6895 fix: the layout error
  config-ui/src/routes/layout/layout.tsx
Labels: needs-cherrypick-v0.21

#6897 fix: icon missed in data scope select
  config-ui/src/routes/blueprint/detail/components/add-connection-dialog/index.tsx
Labels: needs-cherrypick-v0.21
