Repository apache/incubator-devlake, pull requests merged in 2024-04, with the labels that each got.

#7268 feat: gitextractor skips calculating commit stat by default to speed up pipeline
  backend/plugins/gitextractor/gitextractor.go
  backend/plugins/gitextractor/impl/impl.go
  backend/plugins/gitextractor/main.go
  backend/plugins/gitextractor/parser/repo_gogit.go
  backend/plugins/gitextractor/parser/repo_libgit2.go
  backend/plugins/gitextractor/parser/taskdata.go
  backend/plugins/gitextractor/tasks/clone.go
  backend/plugins/gitextractor/tasks/git_repo_collector.go
  env.example
Labels: breaking-change

#7278 feat: gitextactor support `timeAfter` and skipping cloning blobs
  backend/Dockerfile
  backend/go.mod
  backend/go.sum
  backend/plugins/gitextractor/impl/impl.go
  backend/plugins/gitextractor/parser/clone.go
  backend/plugins/gitextractor/parser/clone_gitcli.go
  backend/plugins/gitextractor/parser/clone_gogit.go
  backend/plugins/gitextractor/parser/clone_libgit2.go
  backend/plugins/gitextractor/parser/clone_test.go
  backend/plugins/gitextractor/parser/repo.go
  backend/plugins/gitextractor/parser/repo_creator.go
  backend/plugins/gitextractor/parser/repo_gogit.go
  backend/plugins/gitextractor/parser/repo_libgit2.go
  backend/plugins/gitextractor/parser/repo_test.go
  backend/plugins/gitextractor/parser/taskdata.go
  backend/plugins/gitextractor/tasks/clone.go
Labels: breaking-change

#7301 fix(azuredevops): fix _tool_azuredevops_gitrepositories.id field
  backend/python/plugins/azuredevops/azuredevops/main.py
Labels: pr-type/bug-fix, needs-cherrypick-v0.21, needs-cherrypick-v1.0

#7262 fix: refine process of actions field in Jenkins raw data
  backend/plugins/jenkins/tasks/build_extractor.go
Labels: type/bug, bot/auto-cherry-pick-for-release-v0.21, bot/auto-cherry-pick-for-release-v1.0

#7323 refactor: deprecate specifying timeAfter via `taskOptions`
  backend/plugins/ae/tasks/task_data.go
  backend/plugins/bamboo/models/task_data.go
  backend/plugins/bitbucket/tasks/task_data.go
  backend/plugins/circleci/tasks/task_data.go
  backend/plugins/customize/tasks/task_data.go
  backend/plugins/feishu/tasks/task_data.go
  backend/plugins/gitee/tasks/task_data.go
  backend/plugins/github/tasks/task_data.go
  backend/plugins/gitlab/tasks/task_data.go
  backend/plugins/icla/tasks/task_data.go
  backend/plugins/jenkins/tasks/task_data.go
  backend/plugins/jira/tasks/task_data.go
  backend/plugins/opsgenie/tasks/task_data.go
  backend/plugins/pagerduty/tasks/task_data.go
  backend/plugins/slack/tasks/task_data.go
  backend/plugins/sonarqube/tasks/task_data.go
  backend/plugins/tapd/tasks/task_data.go
  backend/plugins/teambition/tasks/task_data.go
  backend/plugins/trello/tasks/task_data.go
  backend/plugins/zentao/tasks/task_data.go
Labels: breaking-change

#7376 fix: add jira jql checker debug log
  backend/plugins/jira/tasks/board_filter_begin_collector.go
  backend/plugins/jira/tasks/board_filter_end_collector.go
Labels: needs-cherrypick-v0.21

#7389 fix: customize plugin can not update old data
  backend/impls/dalgorm/dalgorm.go
Labels: needs-cherrypick-v0.21

#7366 fix: reduce the entities collected by default
  backend/helpers/pluginhelper/api/pipeline_plan.go
  backend/plugins/jira/tasks/issue_changelog_collector.go
  backend/plugins/jira/tasks/issue_changelog_convertor.go
  backend/plugins/jira/tasks/issue_changelog_extractor.go
  backend/plugins/tapd/tasks/bug_changelog_collector.go
  backend/plugins/tapd/tasks/bug_changelog_converter.go
  backend/plugins/tapd/tasks/bug_changelog_extractor.go
  backend/plugins/zentao/tasks/bug_repo_commits_collector.go
  backend/plugins/zentao/tasks/bug_repo_commits_convertor.go
  backend/plugins/zentao/tasks/bug_repo_commits_extractor.go
  backend/plugins/zentao/tasks/story_repo_commits_collector.go
  backend/plugins/zentao/tasks/story_repo_commits_convertor.go
  backend/plugins/zentao/tasks/story_repo_commits_extractor.go
  backend/plugins/zentao/tasks/task_repo_commits_collector.go
  backend/plugins/zentao/tasks/task_repo_commits_convertor.go
  backend/plugins/zentao/tasks/task_repo_commits_extractor.go
  env.example
Labels: breaking-change

#7403 fix(zentao): update storyID field in tasks reponse, make it compatiab…
  backend/core/models/common/string_int64.go
  backend/helpers/pluginhelper/api/graphql_collector.go
  backend/plugins/zentao/models/task.go
Labels: needs-cherrypick-v0.21
