Repository apache/incubator-devlake, pull requests merged in 2024-03, with the labels that each got.

#7080 feat(plugins): add WRAP_RESPONSE_ERROR in config to avoid SSRF when testing connections
  backend/core/plugin/plugin_api.go
  backend/plugins/ae/api/connection.go
  backend/plugins/bamboo/api/connection_api.go
  backend/plugins/bitbucket/api/connection_api.go
  backend/plugins/circleci/api/connection.go
  backend/plugins/feishu/api/connection.go
  backend/plugins/gitee/api/connection.go
  backend/plugins/github/api/connection_api.go
  backend/plugins/gitlab/api/connection_api.go
  backend/plugins/jenkins/api/connection_api.go
  backend/plugins/jira/api/connection_api.go
  backend/plugins/opsgenie/api/connection.go
  backend/plugins/pagerduty/api/connection.go
  backend/plugins/slack/api/connection.go
  backend/plugins/sonarqube/api/connection_api.go
  backend/plugins/tapd/api/connection.go
  backend/plugins/teambition/api/connection.go
  backend/plugins/trello/api/connection.go
  backend/plugins/zentao/api/connection.go
  env.example
Labels: needs-cherrypick-v0.21, bot/auto-cherry-pick-for-release-v0.21

#7085 fix: show badge in connection name
  config-ui/src/features/connections/components/name.tsx
  config-ui/src/routes/blueprint/detail/configuration-panel.tsx
  config-ui/src/routes/blueprint/detail/styled.ts
Labels: needs-cherrypick-v0.21

#7095 fix: gitlab delate data by raw data table
  backend/plugins/gitlab/e2e/pipelines_detail_test.go
  backend/plugins/gitlab/tasks/mr_comment_convertor.go
  backend/plugins/gitlab/tasks/pipeline_commit_convertor.go
  backend/plugins/gitlab/tasks/pipeline_detail_convertor.go
Labels: needs-cherrypick-v0.21

#7093 fix: sonarqube connection delete on no scope config
  backend/plugins/sonarqube/api/blueprint_v200.go
  backend/plugins/sonarqube/api/init.go
Labels: needs-cherrypick-v0.21

#7104 chore: upgrade miller-columns-select to 1.3.1
  config-ui/package.json
  config-ui/yarn.lock
Labels: needs-cherrypick-v0.20, needs-cherrypick-v0.21

#7112 fix: sonarqube test connection can not effective
  backend/plugins/sonarqube/api/connection_api.go
Labels: needs-cherrypick-v0.21

#7119 fix: cronjob won't work for a new instance
  backend/server/services/blueprint.go
Labels: needs-cherrypick-v0.21

#7122 fix(dora): remove calculated `started_date` when converting pipelines to deployments
  backend/plugins/dora/tasks/deployment_generator.go
Labels: pr-type/bug-fix, needs-cherrypick-v0.21, bot/auto-cherry-pick-for-release-v0.21

#7130 fix(dora): add started_date when generating cicd_deployment_commits
  backend/plugins/dora/tasks/deployment_commits_generator.go
Labels: needs-cherrypick-v0.21, bot/auto-cherry-pick-for-release-v0.21

#7127 fix: missed path prefix
  config-ui/src/config/paths.ts
Labels: needs-cherrypick-v0.21

#7144 fix: missed plugin opsgenie doc
  config-ui/src/plugins/register/opsgenie/config.tsx
  config-ui/src/release/stable.ts
  config-ui/src/release/v0.21.ts
Labels: needs-cherrypick-v0.21

#7148 fix: unable to trigger blueprints with webhooks only
  backend/server/services/blueprint.go
Labels: needs-cherrypick-v0.21

#7152 fix: add connectionId params on swag
  backend/plugins/ae/api/connection.go
  backend/plugins/bamboo/api/connection_api.go
  backend/plugins/bitbucket/api/connection_api.go
  backend/plugins/bitbucket_server/api/connection.go
  backend/plugins/circleci/api/connection.go
  backend/plugins/feishu/api/connection.go
  backend/plugins/gitee/api/connection.go
  backend/plugins/github/api/connection_api.go
  backend/plugins/gitlab/api/connection_api.go
  backend/plugins/jenkins/api/connection_api.go
  backend/plugins/jira/api/connection_api.go
  backend/plugins/opsgenie/api/connection.go
  backend/plugins/pagerduty/api/connection.go
  backend/plugins/slack/api/connection.go
  backend/plugins/sonarqube/api/connection_api.go
  backend/plugins/tapd/api/connection.go
  backend/plugins/teambition/api/connection.go
  backend/plugins/trello/api/connection.go
  backend/plugins/zentao/api/connection.go
Labels: needs-cherrypick-v0.21

#7163 fix: some jira test connection error
  backend/plugins/jira/api/connection_api.go
Labels: needs-cherrypick-v0.21

#7169 fix: limit layout content width to 1280
  config-ui/src/routes/layout/layout.tsx
Labels: needs-cherrypick-v0.21

#7175 fix(zentao): update error message when testing connection fails
  backend/plugins/zentao/models/access_token.go
  backend/plugins/zentao/models/connection.go
Labels: needs-cherrypick-v0.21, bot/auto-cherry-pick-for-release-v0.21

#7183 fix: unnecessary loading
  config-ui/src/plugins/components/data-scope-select/index.tsx
Labels: needs-cherrypick-v0.21, needs-cherrypick-v1.0

#7191 fix: no correct reset state
  config-ui/src/plugins/components/data-scope-remote/search-remote.tsx
Labels: needs-cherrypick-v0.21

#7215 fix: jira jql checker add debug log
  backend/plugins/jira/tasks/board_filter_begin_collector.go
  backend/plugins/jira/tasks/board_filter_end_collector.go
Labels: needs-cherrypick-v0.21
